#!/usr/bin/env python3
"""
gen_blood_profiles.py -- Blood's guns get their own ballistics.

All eight Blood guns were firing in someone else's clothes: the flare gun on a rocket flash and a .45
recoil, the Life Leech on a plasma rifle. The owner: "some of the blood weapons are iconic".

THIS PASS IS THE TWO THAT SHARE A PROBLEM NOTHING IN THE PACKAGE HAD -- a shot whose work STARTS when
it lands instead of resolving there:

  BL_FlareGun   sticks in what it hits and keeps burning. Blood's signature opener.
  BL_Lighter    thrown, tumbles, lands, and burns where it stops -- "lights people on fire like the
                flaregun". Same problem, so the same answer.

WHERE THE FIRE COMES FROM. The owner first said to pull burning sprites out of Bloom and corrected
himself in the same breath: "or don't pull sprites because the blood engine knows what fire damage
is". He is right and it is the better answer -- flame_body, flame_core, flame_licks, flame_tip,
flame_embers, flame_smoke and ember_metal are all this package's own, and a burning man is a
COMPOSITION of them. No source art is taken from anything.

WHAT IS NOT HERE, on purpose. The fire does no HEALTH damage: that is the gun's, the same boundary
that keeps a cartridge from deciding a weapon's damage. `damage` on a hotspot is a scorch brush --
what the fire does to the WALL -- and that one is mine.

    python tools/gen_blood_profiles.py
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFS = os.path.join(HERE, "..", "RSBDEFS.txt")
SND = os.path.join(HERE, "..", "SNDINFO.txt")
BEGIN = "# ---- BEGIN BLOOD (generated by tools/gen_blood_profiles.py) ----"
END = "# ---- END BLOOD ----"

# ---------------------------------------------------------------- the flare, as a real cartridge
# A 26.5 mm flare: a 35 g star lobbed at about 250 fps on a small charge. Low velocity and a lot of
# mass, which is why it reads as a soft heavy shove rather than a crack, and why it flies slowly
# enough to watch. Same free-recoil arithmetic as every other gun in the package.
FLARE_GRAINS, FLARE_FPS, FLARE_CHARGE, FLARE_ROUND = 540, 250, 4.0, 900
FLARE_LB = 2.70          # the sheet's baseweight for BL_FlareGun
ACTION_SEMI = 1.15
CLIMB_PER_FPS = 0.148


def free_recoil(grains, fps, charge, lb):
    vg = (grains * fps + 4700.0 * charge) / (7000.0 * lb)
    return vg, lb * vg * vg / 64.348, lb * vg / 32.174


def blocks():
    vg, energy, impulse = free_recoil(FLARE_GRAINS, FLARE_FPS, FLARE_CHARGE, FLARE_LB)
    climb = vg * CLIMB_PER_FPS * ACTION_SEMI
    out = [BEGIN, ""]

    # ------------------------------------------------------------ THE FIRE ITSELF
    # One hit sets it to full heat and it burns down from there: heat = <per hit>, <cool/s>, <max>,
    # so 1.60 / 0.11 is about fourteen seconds of fire from a single flare.
    out += [
        "# A FIRE THAT RIDES WHAT IT WAS SET ON (`ride`). A hotspot has always been a PLACE -- a beam",
        "# heats a spot on a wall and the spot stays on the wall, which is right for a saw and wrong for",
        "# a fire. Riding, a spot fed by a shot that landed on a THING follows that thing: a burning man",
        "# burns while he runs and carries his own light with him.",
        "#",
        "# ONE HIT SETS IT TO FULL and it burns down: 1.60 of heat against 0.11 a second is about",
        "# fourteen seconds. Nothing feeds it again, which is the whole point -- the shot has left.",
        "hotspot bl_burn            # a flare buried in something, burning it down",
        "  ride       = yes",
        "  merge      = 40",
        "  heat       = 1.60, 0.11, 1.60",
        "  bursts     = flame_body 14, flame_core 9, flame_licks 7, flame_tip 5, flame_embers 4, flame_smoke 6",
        "  light      = 130, 2.4",
        "  lightcolor = 255, 138, 48",
        "  throb      = 7, 0.30",
        "  mark       = pool, 4, 18, 8, 60",
        "  markcolor  = 40, 30, 26",
        "  shimmer    = 20, 1.1",
        "  sound      = rsb/flame/loop, 0.75",
        "  smokevolume = 20, 0.9",
        "  damage     = scorch, 4, 15, 0.35, 0.55, 0.30",
        "end",
        "",
        "# THE LIGHTER'S FIRE: the same fire, smaller and shorter. A zippo is not a flare, and a lighter",
        "# that burned a man down as hard as a signal flare would make the flare gun pointless.",
        "hotspot bl_burn_small      # a lighter lying where it fell, burning what it fell on",
        "  ride       = yes",
        "  merge      = 28",
        "  heat       = 1.00, 0.14, 1.00",
        "  bursts     = flame_body 8, flame_core 5, flame_licks 4, flame_embers 2, flame_smoke 3",
        "  light      = 84, 1.7",
        "  lightcolor = 255, 146, 56",
        "  throb      = 6, 0.34",
        "  mark       = pool, 3, 11, 6, 45",
        "  markcolor  = 40, 30, 26",
        "  shimmer    = 13, 0.8",
        "  sound      = rsb/flame/pilot, 0.7",
        "  smokevolume = 13, 0.6",
        "  damage     = scorch, 3, 9, 0.25, 0.45, 0.22",
        "end",
        "",
    ]

    # ------------------------------------------------------------ WHERE THE FLARE LANDS
    # The impact is deliberately SMALL. Everything a flare does happens over the next fourteen
    # seconds, so a big burst here would spend the moment and leave the fire looking like an
    # afterthought. It lands, it sticks, it catches.
    for suffix, what, bursts in [
        ("", "a flare buried in concrete: it catches and stays caught",
         "flame_splash, flame_embers, spark_hot, dust_concrete"),
        (".metal", "on metal: it skids, throws sparks, and burns where it stops",
         "flame_splash, spark_metal, ember_metal, flame_embers"),
        (".wood", "on wood, which is the one that really takes",
         "flame_splash, flame_licks, splinter_wood, flame_embers"),
        (".flesh", "a flare in a man -- and this is the one the gun is famous for",
         "flame_splash, flame_licks, flame_embers, flame_core"),
        (".dirt", "into dirt: it smothers a little and smokes more",
         "flame_splash, clods_dirt, flame_smoke, flame_embers"),
        (".liquid", "into water: it gutters, hisses and mostly dies",
         "splash_liquid, flame_out_puff, flame_smoke"),
    ]:
        # THE ONE THAT DOES NOT BURN. Water puts a flare out, so .liquid feeds no hotspot -- and the
        # absence is stated here rather than left to a reader to notice.
        burn = "" if suffix == ".liquid" else ("  hotspot    = bl_burn" if suffix != "" else "  hotspot    = bl_burn")
        out += ["impact bl_flare%s   # %s" % (suffix, what),
                "  bursts     = %s" % bursts,
                "  light      = %d, %.1f, %d" % (90 if suffix != ".liquid" else 40, 2.0 if suffix != ".liquid" else 0.8, 9),
                "  lightcolor = 255, 140, 50",
                "  sound      = rsb/flame/hiss1"]
        if burn:
            out.append(burn)
        out += ["end", ""]

    out += [
        "impact bl_lighter          # a lighter that has stopped rolling, and what it does next",
        "  bursts     = flame_licks, flame_embers, flame_splash",
        "  light      = 60, 1.2, 8",
        "  lightcolor = 255, 150, 60",
        "  sound      = rsb/flame/hiss2",
        "  hotspot    = bl_burn_small",
        "end",
        "",
        "impact bl_lighter.flesh    # on a man: the owner's whole reason for throwing it",
        "  bursts     = flame_licks, flame_embers, flame_splash, flame_core",
        "  light      = 70, 1.4, 8",
        "  lightcolor = 255, 150, 60",
        "  sound      = rsb/flame/hiss2",
        "  hotspot    = bl_burn_small",
        "end",
        "",
        "impact bl_lighter.liquid   # it goes out, and that is all",
        "  bursts     = splash_liquid, flame_out_puff",
        "  light      = 24, 0.5, 6",
        "  lightcolor = 255, 150, 60",
        "  sound      = rsb/flame/hiss2",
        "end",
        "",
    ]

    # ------------------------------------------------------------ THE LAST FIVE
    # Two of them fire a real cartridge and are derived like everything else. Three fire nothing that
    # has a load -- burning tar, stolen life, and whatever a Sigil is -- so their kick is STATED, which
    # is a decision rather than an omission and is the same hatch the BFG and the chainsaw already use.
    tommy_lb = 7.00 + 20 * (324 / 7000.0)      # baseweight + a 20-round stick of .45
    sg_lb = 7.00 + 2 * (694 / 7000.0)          # baseweight + two 12 gauge shells
    t_vg, t_e, t_imp = free_recoil(230, 920, 5.0, tommy_lb)
    s_vg, s_e, s_imp = free_recoil(437, 1325, 32.0, sg_lb)
    t_climb = t_vg * CLIMB_PER_FPS * 0.85      # auto
    s_climb = s_vg * CLIMB_PER_FPS * 1.50      # break
    out += [
        "# THE TOMMY GUN. A long barrel gives the .45 920 fps rather than the 1911's 830, and an",
        "# automatic action eats most of what comes back -- so it is a heavy round that arrives as a",
        "# rumble rather than a punch. Derived, not chosen.",
        "flash bl_tommygun         # a broad dirty bloom, ten a second",
        "  light      = 170, 2.4, 2",
        "  lightcolor = 255, 208, 150",
        "  cone       = 20, 54, 100, 5",
        "  conetics   = 2",
        "  bursts     = flash_core, flash_petals, flash_powder",
        "  maybe      = spk_specks 0.4, flash_soot 0.3, powder_clump 0.3",
        "  flame      = 0.09",
        "  smoke      = 3, 0.04, 0.42",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/smg, 0.85",
        "end",
        "",
        "recoil bl_tommygun        # %.1f ft-lb, Vg %.2f fps, impulse %.3f lb-s -- derived" % (t_e, t_vg, t_imp),
        "  climb   = %.2f" % t_climb,
        "  shot    = %.2f, %.1f, %.3f" % (t_vg, t_e, t_imp),
        "  drift   = 0.28, 7",
        "  recover = 14, 5",
        "  max     = %.1f, 3" % max(3.0, min(10.0, 3.0 + 2.2 * t_climb)),
        "  bloom   = 0.03",
        "  brace   = 0.55, 0.8",
        "  view    = 1.5, 4, 1, 5",
        "end",
        "",
        "# BLOOD'S SAWN-OFF. One barrel at a time, and the arithmetic says it is the second hardest",
        "# thing in the set after the flare -- a break action hands nearly all of it back to you.",
        "flash bl_shotgun          # a wide flat gout, and a lot of it",
        "  light      = 240, 3.2, 3",
        "  lightcolor = 255, 214, 158",
        "  cone       = 30, 76, 140, 6",
        "  conetics   = 3",
        "  bursts     = flash_core, flash_petals_wide, flash_plume_wide, flash_powder",
        "  maybe      = flash_embers 0.5, flash_soot 0.45, spk_specks_wide 0.4",
        "  flame      = 0.2",
        "  smoke      = 5, 0.06, 0.6",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/shotgun, 1.0",
        "end",
        "",
        "recoil bl_shotgun         # %.1f ft-lb, Vg %.2f fps, impulse %.3f lb-s -- derived" % (s_e, s_vg, s_imp),
        "  climb   = %.2f" % s_climb,
        "  shot    = %.2f, %.1f, %.3f" % (s_vg, s_e, s_imp),
        "  drift   = 0.34, 4",
        "  recover = 26, 7",
        "  max     = %.1f, 4" % max(3.0, min(10.0, 3.0 + 2.2 * s_climb)),
        "  bloom   = 0.00",
        "  brace   = 0.6, 0.85",
        "  view    = 3.4, 9, 2, 9",
        "end",
        "",
        "# THE NAPALM LAUNCHER, and it is the one gun in the set whose whole point is what happens",
        "# AFTER. It lobs burning tar: the burst where it lands is almost incidental next to the pool",
        "# that stays there. Same `ride` fire as the flare, bigger and longer, and it catches whoever",
        "# is standing in it rather than the floor they are standing on.",
        "hotspot bl_napalm_pool    # what a can of burning tar leaves behind",
        "  ride       = yes",
        "  merge      = 56",
        "  heat       = 2.20, 0.10, 2.20",
        "  bursts     = flame_body 20, flame_core 13, flame_licks 10, flame_tip 7, flame_embers 6, flame_smoke 10",
        "  light      = 170, 2.8",
        "  lightcolor = 255, 132, 44",
        "  throb      = 8, 0.26",
        "  mark       = pool, 8, 30, 10, 90",
        "  markcolor  = 32, 24, 20",
        "  shimmer    = 30, 1.5",
        "  sound      = rsb/flame/loop, 0.9",
        "  smokevolume = 30, 1.2",
        "  damage     = scorch, 8, 26, 0.45, 0.7, 0.35",
        "end",
        "",
        "impact bl_napalm          # it bursts, and then it sits there burning",
        "  bursts     = flame_splash, flame_sheet, flame_embers, flame_smoke, flame_licks",
        "  light      = 190, 3.0, 12",
        "  lightcolor = 255, 138, 46",
        "  sound      = rsb/flame/start",
        "  hotspot    = bl_napalm_pool",
        "end",
        "",
        "impact bl_napalm.flesh    # on a man, which is the same thing except he runs",
        "  bursts     = flame_splash, flame_licks, flame_core, flame_embers",
        "  light      = 180, 2.8, 12",
        "  lightcolor = 255, 138, 46",
        "  sound      = rsb/flame/start",
        "  hotspot    = bl_napalm_pool",
        "end",
        "",
        "impact bl_napalm.liquid   # into water: it goes out, loudly",
        "  bursts     = splash_liquid, flame_out_puff, flame_smoke",
        "  light      = 70, 1.1, 8",
        "  lightcolor = 255, 138, 46",
        "  sound      = rsb/flame/stop",
        "end",
        "",
        "flash bl_napalm           # a wet orange cough out of a home-made tube",
        "  light      = 220, 2.8, 3",
        "  lightcolor = 255, 156, 62",
        "  cone       = 24, 60, 110, 5",
        "  conetics   = 3",
        "  bursts     = flash_core, flash_plume_dirty, flash_embers, flash_soot",
        "  maybe      = flame_licks 0.5, flash_launcher_puff 0.4",
        "  flame      = 0.3",
        "  smoke      = 6, 0.08, 0.7",
        "  smokeparticle = rsb_smoke_rocket",
        "  tail       = rsb/tail/rpg, 0.9   # the only launcher-class tail SNDINFO declares",
        "end",
        "",
        "# STATED, NOT DERIVED: burning tar has no bullet weight and no powder charge, and inventing a",
        "# cartridge so the arithmetic would run is the false precision this package keeps refusing.",
        "recoil bl_napalm          # a heavy wet shove, slow to settle",
        "  climb   = 2.40",
        "  drift   = 0.40, 5",
        "  recover = 20, 7",
        "  max     = 8.0, 4",
        "  bloom   = 0.00",
        "  brace   = 0.6, 0.85",
        "  view    = 3.0, 8, 2, 10",
        "end",
        "",
        "# THE LIFE LEECH: a staff that fires stolen life. It is the only thing in the package that",
        "# should look ORGANIC rather than energetic -- dark red, low, wet, and wrong. Everything else",
        "# we ship that glows is clean; this one should not be.",
        "flash bl_lifeleech        # a dull red pulse, more meat than light",
        "  light      = 120, 1.8, 3",
        "  lightcolor = 190, 26, 34",
        "  cone       = 12, 30, 58, 6",
        "  conetics   = 4",
        "  bursts     = plasma_glow_small, plasma_motes",
        "  maybe      = flesh_char_flecks 0.5, plasma_crackle_muzzle 0.3",
        "  flame      = 0.0",
        "  smoke      = 2, 0.03, 0.3",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/br, 0.7",
        "end",
        "",
        "recoil bl_lifeleech       # stated: a staff drawing life has nothing to push against",
        "  climb   = 0.42",
        "  drift   = 0.18, 9",
        "  recover = 10, 4",
        "  max     = 3.4, 2",
        "  bloom   = 0.01",
        "  brace   = 0.7, 0.9",
        "  view    = 0.8, 3, 1, 4",
        "end",
        "",
        "# THE SIGIL. Blood's last weapon, and it should feel like the room disapproves. Slow, enormous,",
        "# and lit from somewhere other than the muzzle.",
        "flash bl_sigil            # a held breath and then a wave",
        "  light      = 320, 4.2, 4",
        "  lightcolor = 236, 84, 42",
        "  cone       = 40, 96, 170, 7",
        "  conetics   = 4",
        "  bursts     = bfg_glow_heavy, bfg_wave_heavy, bfg_ozone, flash_embers",
        "  maybe      = bfg_arcs 0.6, flame_embers_rise 0.5",
        "  flame      = 0.24",
        "  smoke      = 7, 0.08, 0.75",
        "  smokeparticle = rsb_smoke_flame",
        "  chargebursts = bfg_charge_motes 14, bfg_charge_arcs 8, bfg_charge_core 5",
        "  chargelight = 150, 2.0",
        "  chargelightcolor = 236, 84, 42",
        "  tail       = rsb/tail/rpg, 1.0",
        "end",
        "",
        "recoil bl_sigil           # stated: it does not recoil so much as object",
        "  climb   = 1.90",
        "  drift   = 0.22, 3",
        "  recover = 24, 10",
        "  max     = 6.5, 3",
        "  bloom   = 0.00",
        "  brace   = 0.7, 0.9",
        "  view    = 3.6, 12, 2, 14",
        "end",
        "",
    ]

    # ------------------------------------------------------------ THE SPRAY CAN: TWO JETS, ONE NOZZLE
    # The owner: "i want our blood vr weapons to have the can by itself, firing inert gas. the lighter
    # has to be in the offhand, lit, and in front of the can while it is discharging."
    #
    # That is not a flamethrower with a switch. It is two different things out of one nozzle, and the
    # FIRST of them is the one this package has never had: a jet that is not fire. No light, no heat,
    # no scorch, no sound of its own -- an aerosol is a cold wet nothing that wets what it lands on and
    # hangs in the air. Everything the flame system does is about fire, so almost every key here is
    # deliberately ABSENT rather than turned down.
    #
    # WHICH JET FIRES IS THE GUN'S DECISION, not mine: the can names bl_spray_inert normally and
    # bl_spray_lit while a lit lighter is in front of it. Two named profiles, one switch, and the
    # off-hand lighter stays the hands lane's problem exactly as the main lane ruled.
    out += [
        "# COLD AEROSOL: fine propellant, mostly invisible, faintly grey where it is dense. It travels",
        "# far less than a flame because nothing is driving it but can pressure, and it FALLS -- gravity",
        "# on the droplets is what makes it read as a liquid rather than a gas.",
        "burst spray_mist          # the jet itself: a fine cold fan of propellant",
        "  count    = 4",
        "  cone     = 13",
        "  speed    = 120, 0.45",
        "  life     = 0.55, 0.35",
        "  size     = 0.8, 0.4",
        "  gravity  = 0.25",
        "  drag     = 0.14",
        "  color    = 214, 216, 218",
        "  particle = rsb_smoke_gun",
        "end",
        "",
        "burst spray_haze          # what hangs behind it: slower, wider, and it lingers",
        "  count    = 2",
        "  cone     = 34",
        "  speed    = 34, 0.6",
        "  life     = 1.9, 0.4",
        "  size     = 1.7, 0.5",
        "  gravity  = 0.05",
        "  drag     = 0.3",
        "  color    = 206, 209, 212",
        "  particle = rsb_smoke_gun",
        "end",
        "",
        "burst spray_wet           # where it lands: it wets the surface and creeps a moment",
        "  count    = 3",
        "  cone     = 62",
        "  speed    = 46, 0.5",
        "  life     = 1.1, 0.3",
        "  size     = 1.1, 0.4",
        "  gravity  = 0.4",
        "  drag     = 0.22",
        "  color    = 200, 204, 208",
        "  particle = rsb_smoke_gun",
        "end",
        "",
        "# THE CAN ON ITS OWN. No light, no heat, no scorch and no sound: the gun's own firesound is the",
        "# hiss, and a loop here would double it. `cling` is the only thing it shares with a flame --",
        "# propellant does run down a wall. Everything else fire does is simply not stated.",
        "flame bl_spray_inert      # an aerosol can, discharging: cold, wet, and harmless",
        "  reach       = 150",
        "  speed       = 420",
        "  spread      = 3.4",
        "  stream      = spray_mist, spray_haze",
        "  landing     = spray_wet, spray_haze",
        "  landingtics = 3",
        "  cling       = 0.22",
        "  sounds      = none, none, none",
        "end",
        "",
        "# AND THE SAME CAN WITH A LIT ZIPPO IN FRONT OF IT. Shorter than the Flammenwerfer and thinner",
        "# -- a spray can is not a military flamethrower and should never read like one -- but it is the",
        "# same cold jet with the fire riding on it, so the mist bursts stay in the stream: the unburnt",
        "# propellant at the edges is what makes an improvised flamethrower look improvised.",
        "flame bl_spray_lit        # the can and the lighter, which is the whole joke of the weapon",
        "  reach       = 210",
        "  speed       = 460",
        "  spread      = 3.0",
        "  stream      = flame_core, flame_body, flame_tip, spray_mist",
        "  landing     = flame_splash, flame_lick, flame_smoke, spray_wet",
        "  landingtics = 2",
        "  cling       = 0.26",
        "  tube        = 5, 0.85, 3, 0.45",
        "  tubelook    = 1.4, 2.6, 0.55",
        "  tubecolors  = 255, 244, 214, 255, 198, 104, 255, 124, 34, 182, 52, 10, 96, 20, 5",
        "  tubelicks   = 0.62, 0.08, 2.0",
        "  heat        = 4, 15, 1.0, 0.08, 26",
        "  heatland    = 24, 1.15",
        "  scorch      = pool, 9, 95",
        "  scorchcolor = 255, 92, 20",
        "  scorchtics  = 10",
        "  light       = 190, 2.2, 0.42",
        "  lightcolor  = 255, 148, 58",
        "  landlight   = 130, 1.9",
        "  sounds      = rsb/flame/loop, rsb/flame/start, rsb/flame/stop",
        "  sputter     = 0.3, rsb/flame/hiss",
        "end",
        "",
    ]

    # ------------------------------------------------------------ THE FLARE IN FLIGHT
    out += [
        "ballistics bl_flare        # a 26.5 mm star: heavy, slow, and you watch it go",
        "  speed  = 26",
        "  radius = 3.0",
        "  roundmass = %d   # one loaded round, grains (7000 = 1 lb)" % FLARE_ROUND,
        "  damage = none",
        "end",
        "",
        "# IT IS THE BRIGHTEST THING IN THE ROOM WHILE IT FLIES. A flare is a light source that happens",
        "# to be travelling, so it gets the heavy tracer's model, a burning wake and a comet of light --",
        "# and at 26 units a tic it is slow enough to actually watch, which is the point of the weapon.",
        "roundlook bl_flare",
        "  look      = model, RSBMH",
        "  glide     = yes",
        "  wake      = tracer_hot_heavy",
        "  impact    = bl_flare",
        "  whiz      = 60, rsb/whiz",
        "  light     = 96, 2.2",
        "  lightcolor = 255, 140, 46",
        "  lightlook = comet",
        "  heat      = 7, 0.7, 14",
        "end",
        "",
        "round bl_flare",
        "  ballistics = bl_flare",
        "  roundlook  = bl_flare",
        "end",
        "",
    ]

    # ------------------------------------------------------------ THE GUN
    out += [
        "# A FLARE PISTOL DOES NOT CRACK, IT WHUMPS. A small charge behind a heavy star: a fat soft",
        "# bloom of orange, a lot of light, and no sharp edge to it at all.",
        "flash bl_flaregun          # the launch: soft, wide, and very orange",
        "  bursts     = flash_core, flash_petals_wide, flash_plume_wide, flash_embers, flash_soot",
        "  cone       = 26, 62, 120, 7",
        "  conetics   = 3",
        "  flame      = 0.22",
        "  light      = 150, 2.6, 3",
        "  lightcolor = 255, 146, 52",
        "  smoke      = 4, 0.05, 0.55",
        "  tail       = rsb/tail/shotgun, 0.7",
        "end",
        "",
        "# %.1f ft-lb, Vg %.2f fps, impulse %.3f lb-s -- a 540 gr star at %d fps out of a %.2f lb pistol.",
        "# Derived, not chosen: same arithmetic as every other gun here.",
        "recoil bl_flaregun         # a slow heavy shove, not a snap",
        "  climb   = %.2f",
        "  shot    = %.2f, %.1f, %.3f",
        "  drift   = 0.35, 5",
        "  recover = 22, 6",
        "  max     = %.1f, 3",
        "  bloom   = 0.00",
        "  brace   = 0.6, 0.85",
        "  view    = 2.6, 7, 1, 8",
        "end",
        "",
        END, "",
    ]
    # fill the recoil numbers in
    out = [ln % (energy, vg, impulse, FLARE_FPS, FLARE_LB) if ln.startswith("# %.1f ft-lb") else ln for ln in out]
    out = [ln % climb if ln.startswith("  climb   = %.2f") else ln for ln in out]
    out = [ln % (vg, energy, impulse) if ln.startswith("  shot    = %.2f") else ln for ln in out]
    out = [ln % max(3.0, min(10.0, 3.0 + 2.2 * climb)) if ln.startswith("  max     = %.1f") else ln for ln in out]
    return out, climb, vg, energy, impulse


def check_sounds(body):
    """Refuse to write a sound name SNDINFO does not declare. A dead sound name is silent and looks fine."""
    declared = set()
    for line in io.open(SND, encoding="utf-8", errors="replace"):
        s = line.split("//")[0].strip()
        for kw in ("$random", "$alias", "$playersound", "$limit", "$pitchset", "$volume"):
            if s.lower().startswith(kw):
                s = s[len(kw):].strip()
                break
        m = re.match(r"^([A-Za-z0-9_/\-]+)", s)
        if m:
            declared.add(m.group(1).lower())
    bad = []
    for ln in body:
        m = re.match(r"^\s*(sound|tail)\s*=\s*([A-Za-z0-9_/\-]+)", ln)
        if not m:
            continue
        n = m.group(2).lower()
        if n in ("none", "") or n in declared:
            continue
        if (n + "/int") in declared or (n + "/ext") in declared:
            continue
        bad.append(m.group(2))
    if bad:
        raise SystemExit("REFUSING TO WRITE: these sound names are not declared in SNDINFO and would "
                         "be silent:\n  " + "\n  ".join(sorted(set(bad))))


# WHAT THE WEAPONS LANE PUTS ON THE SHEET. Printed rather than messaged, so the names come from the
# same file that wrote the profiles and cannot drift from them -- a name typed into a chat window is
# a second copy that nothing checks.
SHEET = [
    ("BL_FlareGun", [
        ("flashprofile", "bl_flaregun", "was `rocket` -- a launcher's flash on a flare pistol"),
        ("recoilprofile", "bl_flaregun", "was `pistol_45`; this one is derived from the flare itself"),
        ("roundprofile", "bl_flare", "the star in flight, and what it does where it lands"),
    ]),
    ("BL_TommyGun", [
        ("flashprofile", "bl_tommygun", "was the generic `smg`"),
        ("recoilprofile", "bl_tommygun", "derived: a .45 at 920 fps out of your 7.00 lb, auto action"),
    ]),
    ("BL_Shotgun", [
        ("flashprofile", "bl_shotgun", "was `shotgun_doublebarrel`"),
        ("recoilprofile", "bl_shotgun", "derived: one barrel, break action -- the hardest kick in the set after the flare"),
    ]),
    ("BL_Napalm", [
        ("flashprofile", "bl_napalm", "was `rocket_launcher`"),
        ("recoilprofile", "bl_napalm", "stated: burning tar has no load to derive from"),
        (None, None, "NO roundprofile. `bl_napalm` is an IMPACT, not a round -- a lobbed canister "
                     "has no round in flight. BL_NapalmRocket names it where it lands: "
                     "RSB_Impact.Land(self, \"bl_napalm\", vel). It leaves a burning pool that RIDES "
                     "whoever is standing in it."),
    ]),
    ("BL_LifeLeech", [
        ("flashprofile", "bl_lifeleech", "was `plasma_rifle`; this one is organic, not energetic"),
        ("recoilprofile", "bl_lifeleech", "stated"),
    ]),
    ("BL_Sigil", [
        ("flashprofile", "bl_sigil", "was the generic `bfg`"),
        ("recoilprofile", "bl_sigil", "stated"),
    ]),
    ("BL_SprayCan", [
        (None, None, "NO SHEET KEY, and no new one is needed. A flame gun does not name its profile "
                     "on the sheet at all -- WM_FlameGun.FlameProfile() is a VIRTUAL, which is why "
                     "`flameprofile` is absent from the reader: nothing has ever wanted it."),
        (None, None, "AND A SHEET KEY COULD NOT WORK HERE ANYWAY. A key states ONE name. The whole "
                     "point of this weapon is that which jet comes out depends on something only the "
                     "weapon can see -- whether a lit lighter is in front of the nozzle. A condition "
                     "is code; the two names are data. Keep them on the right sides of that line."),
        (None, None, "SO: make BL_SprayCan a WM_FlameGun (it is generated as a plain WM_Gun today, "
                     "which is why it has no flame at all) and override the virtual: return "
                     "\"bl_spray_lit\" when the lighter is lit and in front, \"bl_spray_inert\" "
                     "otherwise. No ask of the reload lane, no new key, no key that can be stated "
                     "wrong."),
        (None, None, "IF a second weapon ever needs the same pairing, the shape to ask for then is "
                     "TWO keys (flameprofile and litflameprofile), not one -- but building that for "
                     "a single caller is a key nobody consults, which is the failure we keep finding."),
    ]),
    ("BL_Lighter", [
        (None, None, "NO SHEET KEY. It is thrown, so there is no round in flight for a roundprofile "
                     "to describe -- the class names the impact where the impact happens: "
                     "RSB_Impact.Land(self, \"bl_lighter\", vel) in its Death state."),
    ]),
]


def wrap(t, width=86):
    out, line = [], ""
    for w in t.split():
        if len(line) + len(w) + 1 > width:
            out.append(line); line = w
        else:
            line = (line + " " + w).strip()
    if line:
        out.append(line)
    return out


def print_sheet():
    print("SHEET KEYS FOR THE WEAPONS LANE -- Blood")
    print()
    for gun, keys in SHEET:
        print('gun "%s"' % gun)
        for k, v, why in keys:
            # A NOTE WITH NO KEY. The weapons lane took `roundprofile = "bl_napalm"` literally --
            # correctly, it was printed as a sheet line -- and their lint refused it, because
            # bl_napalm is an impact and no `round bl_napalm` exists. The NOTE underneath was the
            # real instruction and the line above it said the opposite. A tool that prints a key it
            # then talks you out of is a tool that has invented work, so it no longer prints one.
            if k is None:
                for chunk in wrap(why):
                    print("  # %s" % chunk)
                continue
            print('  %-20s = "%s"' % (k, v))
            for chunk in wrap(why):
                print('  %s# %s' % (" " * 20, chunk))
        print()
    print("BL_TommyGun and BL_Shotgun keep their EJECTA as they are: brass_45 and hull_12ga are")
    print("exactly what those guns throw, so that was never borrowing, it was correct reuse.")
    print("BL_TeslaGun keeps ww2_tesla on purpose: two tesla weapons should look the same.")
    print("Nothing in Blood is borrowed after this.")


def main():
    if "--sheet" in sys.argv:
        print_sheet()
        return
    body, climb, vg, energy, impulse = blocks()
    check_sounds(body)
    text = io.open(DEFS, encoding="utf-8", newline="").read()
    nl = "\r\n" if "\r\n" in text else "\n"
    block = nl.join(body)
    if BEGIN in text:
        i, j = text.index(BEGIN), text.index(END) + len(END) + len(nl)
        text = text[:i] + block + text[j:]
    else:
        anchor = "# ---- END NEW SETS"
        if anchor not in text:
            raise SystemExit("no anchor to insert before")
        text = text.replace(anchor, block + anchor, 1)
    io.open(DEFS, "w", encoding="utf-8", newline="").write(text)
    n = len([l for l in body if re.match(r"^(hotspot|impact|flash|recoil|ballistics|roundlook|round|burst|flame) ", l)])
    print("%d Blood profiles written." % n)
    print("flare gun: Vg %.2f fps, %.1f ft-lb, impulse %.3f lb-s -> climb %.2f" % (vg, energy, impulse, climb))
    print("the fire: bl_burn rides for ~%.0f s, bl_burn_small for ~%.0f s" % (1.60 / 0.11, 1.00 / 0.14))


main()
