#!/usr/bin/env python3
"""
gen_blood_profiles.py -- Blood's guns get their own ballistics.

All eight Blood guns were firing in someone else's clothes: the flare gun on a rocket flash and a .45
recoil, the Life Leech on a plasma rifle. The owner: "some of the blood weapons are iconic".

THIS PASS IS THE TWO THAT SHARE A PROBLEM NOTHING IN THE PACKAGE HAD -- a shot whose work STARTS when
it lands instead of resolving there:

  BL_FlareGun   sticks in what it hits and keeps burning. Blood's signature opener.
  BL_Lighter    thrown, tumbles, lands, and burns where it stops -- "lights people on fire like the
                flaregun". Same problem, so the same answer.

WHERE THE FIRE COMES FROM. The owner first said to pull burning sprites out of Bloom and corrected
himself in the same breath: "or don't pull sprites because the blood engine knows what fire damage
is". He is right and it is the better answer -- flame_body, flame_core, flame_licks, flame_tip,
flame_embers, flame_smoke and ember_metal are all this package's own, and a burning man is a
COMPOSITION of them. No source art is taken from anything.

WHAT IS NOT HERE, on purpose. The fire does no HEALTH damage: that is the gun's, the same boundary
that keeps a cartridge from deciding a weapon's damage. `damage` on a hotspot is a scorch brush --
what the fire does to the WALL -- and that one is mine.

    python tools/gen_blood_profiles.py
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFS = os.path.join(HERE, "..", "RSBDEFS.txt")
SND = os.path.join(HERE, "..", "SNDINFO.txt")
BEGIN = "# ---- BEGIN BLOOD (generated by tools/gen_blood_profiles.py) ----"
END = "# ---- END BLOOD ----"

# ---------------------------------------------------------------- the flare, as a real cartridge
# A 26.5 mm flare: a 35 g star lobbed at about 250 fps on a small charge. Low velocity and a lot of
# mass, which is why it reads as a soft heavy shove rather than a crack, and why it flies slowly
# enough to watch. Same free-recoil arithmetic as every other gun in the package.
FLARE_GRAINS, FLARE_FPS, FLARE_CHARGE, FLARE_ROUND = 540, 250, 4.0, 900
FLARE_LB = 2.70          # the sheet's baseweight for BL_FlareGun
ACTION_SEMI = 1.15
CLIMB_PER_FPS = 0.148


def free_recoil(grains, fps, charge, lb):
    vg = (grains * fps + 4700.0 * charge) / (7000.0 * lb)
    return vg, lb * vg * vg / 64.348, lb * vg / 32.174


def blocks():
    vg, energy, impulse = free_recoil(FLARE_GRAINS, FLARE_FPS, FLARE_CHARGE, FLARE_LB)
    climb = vg * CLIMB_PER_FPS * ACTION_SEMI
    out = [BEGIN, ""]

    # ------------------------------------------------------------ THE FIRE ITSELF
    # One hit sets it to full heat and it burns down from there: heat = <per hit>, <cool/s>, <max>,
    # so 1.60 / 0.11 is about fourteen seconds of fire from a single flare.
    out += [
        "# A FIRE THAT RIDES WHAT IT WAS SET ON (`ride`). A hotspot has always been a PLACE -- a beam",
        "# heats a spot on a wall and the spot stays on the wall, which is right for a saw and wrong for",
        "# a fire. Riding, a spot fed by a shot that landed on a THING follows that thing: a burning man",
        "# burns while he runs and carries his own light with him.",
        "#",
        "# ONE HIT SETS IT TO FULL and it burns down: 1.60 of heat against 0.11 a second is about",
        "# fourteen seconds. Nothing feeds it again, which is the whole point -- the shot has left.",
        "hotspot bl_burn            # a flare buried in something, burning it down",
        "  ride       = yes",
        "  merge      = 40",
        "  heat       = 1.60, 0.11, 1.60",
        "  bursts     = flame_body 14, flame_core 9, flame_licks 7, flame_tip 5, flame_embers 4, flame_smoke 6",
        "  light      = 130, 2.4",
        "  lightcolor = 255, 138, 48",
        "  throb      = 7, 0.30",
        "  mark       = pool, 4, 18, 8, 60",
        "  markcolor  = 40, 30, 26",
        "  shimmer    = 20, 1.1",
        "  sound      = rsb/flame/loop, 0.75",
        "  smokevolume = 20, 0.9",
        "  damage     = scorch, 4, 15, 0.35, 0.55, 0.30",
        "end",
        "",
        "# THE LIGHTER'S FIRE: the same fire, smaller and shorter. A zippo is not a flare, and a lighter",
        "# that burned a man down as hard as a signal flare would make the flare gun pointless.",
        "hotspot bl_burn_small      # a lighter lying where it fell, burning what it fell on",
        "  ride       = yes",
        "  merge      = 28",
        "  heat       = 1.00, 0.14, 1.00",
        "  bursts     = flame_body 8, flame_core 5, flame_licks 4, flame_embers 2, flame_smoke 3",
        "  light      = 84, 1.7",
        "  lightcolor = 255, 146, 56",
        "  throb      = 6, 0.34",
        "  mark       = pool, 3, 11, 6, 45",
        "  markcolor  = 40, 30, 26",
        "  shimmer    = 13, 0.8",
        "  sound      = rsb/flame/pilot, 0.7",
        "  smokevolume = 13, 0.6",
        "  damage     = scorch, 3, 9, 0.25, 0.45, 0.22",
        "end",
        "",
    ]

    # ------------------------------------------------------------ WHERE THE FLARE LANDS
    # The impact is deliberately SMALL. Everything a flare does happens over the next fourteen
    # seconds, so a big burst here would spend the moment and leave the fire looking like an
    # afterthought. It lands, it sticks, it catches.
    for suffix, what, bursts in [
        ("", "a flare buried in concrete: it catches and stays caught",
         "flame_splash, flame_embers, spark_hot, dust_concrete"),
        (".metal", "on metal: it skids, throws sparks, and burns where it stops",
         "flame_splash, spark_metal, ember_metal, flame_embers"),
        (".wood", "on wood, which is the one that really takes",
         "flame_splash, flame_licks, splinter_wood, flame_embers"),
        (".flesh", "a flare in a man -- and this is the one the gun is famous for",
         "flame_splash, flame_licks, flame_embers, flame_core"),
        (".dirt", "into dirt: it smothers a little and smokes more",
         "flame_splash, clods_dirt, flame_smoke, flame_embers"),
        (".liquid", "into water: it gutters, hisses and mostly dies",
         "splash_liquid, flame_out_puff, flame_smoke"),
    ]:
        # THE ONE THAT DOES NOT BURN. Water puts a flare out, so .liquid feeds no hotspot -- and the
        # absence is stated here rather than left to a reader to notice.
        burn = "" if suffix == ".liquid" else ("  hotspot    = bl_burn" if suffix != "" else "  hotspot    = bl_burn")
        out += ["impact bl_flare%s   # %s" % (suffix, what),
                "  bursts     = %s" % bursts,
                "  light      = %d, %.1f, %d" % (90 if suffix != ".liquid" else 40, 2.0 if suffix != ".liquid" else 0.8, 9),
                "  lightcolor = 255, 140, 50",
                "  sound      = rsb/flame/hiss1"]
        if burn:
            out.append(burn)
        out += ["end", ""]

    out += [
        "impact bl_lighter          # a lighter that has stopped rolling, and what it does next",
        "  bursts     = flame_licks, flame_embers, flame_splash",
        "  light      = 60, 1.2, 8",
        "  lightcolor = 255, 150, 60",
        "  sound      = rsb/flame/hiss2",
        "  hotspot    = bl_burn_small",
        "end",
        "",
        "impact bl_lighter.flesh    # on a man: the owner's whole reason for throwing it",
        "  bursts     = flame_licks, flame_embers, flame_splash, flame_core",
        "  light      = 70, 1.4, 8",
        "  lightcolor = 255, 150, 60",
        "  sound      = rsb/flame/hiss2",
        "  hotspot    = bl_burn_small",
        "end",
        "",
        "impact bl_lighter.liquid   # it goes out, and that is all",
        "  bursts     = splash_liquid, flame_out_puff",
        "  light      = 24, 0.5, 6",
        "  lightcolor = 255, 150, 60",
        "  sound      = rsb/flame/hiss2",
        "end",
        "",
    ]

    # ------------------------------------------------------------ THE FLARE IN FLIGHT
    out += [
        "ballistics bl_flare        # a 26.5 mm star: heavy, slow, and you watch it go",
        "  speed  = 26",
        "  radius = 3.0",
        "  roundmass = %d   # one loaded round, grains (7000 = 1 lb)" % FLARE_ROUND,
        "  damage = none",
        "end",
        "",
        "# IT IS THE BRIGHTEST THING IN THE ROOM WHILE IT FLIES. A flare is a light source that happens",
        "# to be travelling, so it gets the heavy tracer's model, a burning wake and a comet of light --",
        "# and at 26 units a tic it is slow enough to actually watch, which is the point of the weapon.",
        "roundlook bl_flare",
        "  look      = model, RSBMH",
        "  glide     = yes",
        "  wake      = tracer_hot_heavy",
        "  impact    = bl_flare",
        "  whiz      = 60, rsb/whiz",
        "  light     = 96, 2.2",
        "  lightcolor = 255, 140, 46",
        "  lightlook = comet",
        "  heat      = 7, 0.7, 14",
        "end",
        "",
        "round bl_flare",
        "  ballistics = bl_flare",
        "  roundlook  = bl_flare",
        "end",
        "",
    ]

    # ------------------------------------------------------------ THE GUN
    out += [
        "# A FLARE PISTOL DOES NOT CRACK, IT WHUMPS. A small charge behind a heavy star: a fat soft",
        "# bloom of orange, a lot of light, and no sharp edge to it at all.",
        "flash bl_flaregun          # the launch: soft, wide, and very orange",
        "  bursts     = flash_core, flash_petals_wide, flash_plume_wide, flash_embers, flash_soot",
        "  cone       = 26, 62, 120, 7",
        "  conetics   = 3",
        "  flame      = 0.22",
        "  light      = 150, 2.6, 3",
        "  lightcolor = 255, 146, 52",
        "  smoke      = 4, 0.05, 0.55",
        "  tail       = rsb/tail/shotgun, 0.7",
        "end",
        "",
        "# %.1f ft-lb, Vg %.2f fps, impulse %.3f lb-s -- a 540 gr star at %d fps out of a %.2f lb pistol.",
        "# Derived, not chosen: same arithmetic as every other gun here.",
        "recoil bl_flaregun         # a slow heavy shove, not a snap",
        "  climb   = %.2f",
        "  shot    = %.2f, %.1f, %.3f",
        "  drift   = 0.35, 5",
        "  recover = 22, 6",
        "  max     = %.1f, 3",
        "  bloom   = 0.00",
        "  brace   = 0.6, 0.85",
        "  view    = 2.6, 7, 1, 8",
        "end",
        "",
        END, "",
    ]
    # fill the recoil numbers in
    out = [ln % (energy, vg, impulse, FLARE_FPS, FLARE_LB) if ln.startswith("# %.1f ft-lb") else ln for ln in out]
    out = [ln % climb if ln.startswith("  climb   = %.2f") else ln for ln in out]
    out = [ln % (vg, energy, impulse) if ln.startswith("  shot    = %.2f") else ln for ln in out]
    out = [ln % max(3.0, min(10.0, 3.0 + 2.2 * climb)) if ln.startswith("  max     = %.1f") else ln for ln in out]
    return out, climb, vg, energy, impulse


def check_sounds(body):
    """Refuse to write a sound name SNDINFO does not declare. A dead sound name is silent and looks fine."""
    declared = set()
    for line in io.open(SND, encoding="utf-8", errors="replace"):
        s = line.split("//")[0].strip()
        for kw in ("$random", "$alias", "$playersound", "$limit", "$pitchset", "$volume"):
            if s.lower().startswith(kw):
                s = s[len(kw):].strip()
                break
        m = re.match(r"^([A-Za-z0-9_/\-]+)", s)
        if m:
            declared.add(m.group(1).lower())
    bad = []
    for ln in body:
        m = re.match(r"^\s*(sound|tail)\s*=\s*([A-Za-z0-9_/\-]+)", ln)
        if not m:
            continue
        n = m.group(2).lower()
        if n in ("none", "") or n in declared:
            continue
        if (n + "/int") in declared or (n + "/ext") in declared:
            continue
        bad.append(m.group(2))
    if bad:
        raise SystemExit("REFUSING TO WRITE: these sound names are not declared in SNDINFO and would "
                         "be silent:\n  " + "\n  ".join(sorted(set(bad))))


# WHAT THE WEAPONS LANE PUTS ON THE SHEET. Printed rather than messaged, so the names come from the
# same file that wrote the profiles and cannot drift from them -- a name typed into a chat window is
# a second copy that nothing checks.
SHEET = [
    ("BL_FlareGun", [
        ("flashprofile", "bl_flaregun", "was `rocket` -- a launcher's flash on a flare pistol"),
        ("recoilprofile", "bl_flaregun", "was `pistol_45`; this one is derived from the flare itself"),
        ("roundprofile", "bl_flare", "the star in flight, and what it does where it lands"),
    ]),
    ("BL_Lighter", [
        ("roundprofile", "bl_lighter", "NOTE: it is thrown, so whatever BL_ThrownLighter calls on "
                                       "landing must name the impact `bl_lighter`; if the class does "
                                       "not read roundprofile, tell me and I will meet it where it is"),
    ]),
]


def print_sheet():
    print("SHEET KEYS FOR THE WEAPONS LANE -- Blood, pass 1 of 3")
    print()
    for gun, keys in SHEET:
        print('gun "%s"' % gun)
        for k, v, why in keys:
            print('  %-20s = "%s"' % (k, v))
            print('  %s# %s' % (" " * 20, why))
        print()
    print("Still borrowed and coming in the next two passes: BL_SprayCan (two jets, one nozzle --")
    print("inert gas and ignited), then BL_TommyGun, BL_Shotgun, BL_Napalm, BL_LifeLeech, BL_Sigil.")
    print("BL_TeslaGun keeps ww2_tesla on purpose: two tesla weapons should look the same.")


def main():
    if "--sheet" in sys.argv:
        print_sheet()
        return
    body, climb, vg, energy, impulse = blocks()
    check_sounds(body)
    text = io.open(DEFS, encoding="utf-8", newline="").read()
    nl = "\r\n" if "\r\n" in text else "\n"
    block = nl.join(body)
    if BEGIN in text:
        i, j = text.index(BEGIN), text.index(END) + len(END) + len(nl)
        text = text[:i] + block + text[j:]
    else:
        anchor = "# ---- END NEW SETS"
        if anchor not in text:
            raise SystemExit("no anchor to insert before")
        text = text.replace(anchor, block + anchor, 1)
    io.open(DEFS, "w", encoding="utf-8", newline="").write(text)
    n = len([l for l in body if re.match(r"^(hotspot|impact|flash|recoil|ballistics|roundlook|round) ", l)])
    print("%d Blood profiles written." % n)
    print("flare gun: Vg %.2f fps, %.1f ft-lb, impulse %.3f lb-s -> climb %.2f" % (vg, energy, impulse, climb))
    print("the fire: bl_burn rides for ~%.0f s, bl_burn_small for ~%.0f s" % (1.60 / 0.11, 1.00 / 0.14))


main()
