#!/usr/bin/env python3
"""
gen_starwars_profiles.py -- Star Wars: bolts you can watch fly, and a lightsaber that melts walls.

The owner, 2026-09-21: "make sure the ballistics are beautiful lovely beams ... but remember it is
star wars, not john wick." And straight after: "ballistics should still add weight and recoil here
and there. i need some feedback at least."

EVERY INSTINCT THIS PACKAGE HAS IS JOHN WICK -- brass, powder smoke, flash petals, a cartridge's
arithmetic. Every one of those is wrong here. So:

  NO BRASS         every gun states `ejecta none`
  NO POWDER SMOKE  a blaster flash is a coloured snap of light and a whiff of ozone
  NO HITSCAN       a bolt is a glowing streak that FLIES, slowly enough to follow with your eye, and
                   lights the walls it passes
  NEVER ZERO KICK  there is no cartridge to derive one from, so every kick is STATED -- lighter and
                   sharper than a gun's, but present, because an energy weapon with no kick is a toy

WHAT A BOLT IS: the round-in-flight mesh this package already flies (models/bullet/btracer.obj), in a
coloured skin generated from its own texture -- the white-hot core kept, the orange edge recoloured --
at its own size. THE FILMS' COLOURS (owner, 2026-09-21): hand blasters fire RED on both sides --
Han's, Leia's, the Rebel troopers' -- blue is the clone army and ion, and the bowcaster keeps the green
the games gave it. An earlier draft said "red Empire, green Rebel"; that came from a brief, not from
the owner, and it is not what the films show.

THE SABER'S LOOK IS HERE; the blade, the throw and the deflect logic are the weapons lane's. Eight
colours, each with a deflect, a cut, a wall melt that drags with the blade (the blast-door shot), a
swing smear, and a clash.

    python tools/gen_starwars_profiles.py            write the profiles
    python tools/gen_starwars_profiles.py --sheet    the sheet lines for the weapons lane
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
DEFS = os.path.join(PKG, "RSBDEFS.txt")
SND = os.path.join(PKG, "SNDINFO.txt")
MODELDEF = os.path.join(PKG, "MODELDEF.txt")
BEGIN = "# ---- BEGIN STAR WARS (generated by tools/gen_starwars_profiles.py) ----"
END = "# ---- END STAR WARS ----"
MD_BEGIN = "// ---- BEGIN STAR WARS BOLTS (generated by tools/gen_starwars_profiles.py) ----"
MD_END = "// ---- END STAR WARS BOLTS ----"

# ---------------------------------------------------------------- the colours
BOLT = {
    "red":   (255, 60, 50),     # almost every hand blaster in the films, on both sides
    "green": (90, 255, 110),    # the bowcaster (the games' colour for it)
    "blue":  (100, 160, 255),   # the clone army
    "ion":   (185, 228, 255),   # ion: nearly white, a cold blue edge
}

# ---------------------------------------------------------------- the bolts in flight
# frame letter on the RSBM sprite -> (skin colour, length, width, note). btracer.obj is 80 long and
# 7 across; a bolt is FATTER than a bullet for its length, because it is a glow and not a slug.
FRAMES = {
    "I": ("red",   22, 2.6, "a red pistol bolt"),
    "J": ("red",   30, 3.0, "a red rifle bolt"),
    "K": ("red",   40, 3.8, "a red heavy bolt"),
    "L": ("red",   64, 2.0, "a red sniper bolt: the longest and thinnest"),
    "M": ("green", 22, 2.6, "a green pistol bolt"),
    "N": ("green", 30, 3.0, "a green rifle bolt"),
    "O": ("green", 40, 3.8, "a green heavy bolt"),
    "P": ("green", 34, 5.2, "a bowcaster quarrel: fat, and it hits"),
    "Q": ("blue",  30, 3.0, "a blue rifle bolt"),
    "R": ("blue",  40, 3.8, "a blue heavy bolt"),
    "S": ("ion",   32, 3.6, "an ion bolt"),
    "T": ("red",   26, 9.0, "a heavy charge: a short fat blob, the assault cannon"),
    "U": ("ion",   20, 11.0, "a concussion pulse: a pale blob of pressure"),
}

# round id -> (frame, colour, speed units/tic, radius, whiz)
# SLOW ENOUGH TO WATCH. A bullet here flies at 250-620 units a tic and is a streak you never see. A
# film blaster bolt is something you track across the room, so these are a fraction of that.
ROUNDS = {
    "sw_bolt_red_pistol":   ("I", "red",   62, 3.0, 56),
    "sw_bolt_red_rifle":    ("J", "red",   72, 3.0, 60),
    "sw_bolt_red_heavy":    ("K", "red",   60, 3.5, 64),
    "sw_bolt_red_sniper":   ("L", "red",   130, 2.5, 72),
    "sw_bolt_green_pistol": ("M", "green", 62, 3.0, 56),
    "sw_bolt_green_rifle":  ("N", "green", 72, 3.0, 60),
    "sw_bolt_green_heavy":  ("O", "green", 60, 3.5, 64),
    "sw_bolt_green_quarrel": ("P", "green", 46, 4.5, 64),
    "sw_bolt_blue_rifle":   ("Q", "blue",  72, 3.0, 60),
    "sw_bolt_blue_heavy":   ("R", "blue",  60, 3.5, 64),
    "sw_bolt_ion":          ("S", "ion",   64, 3.5, 60),
    "sw_bolt_red_charge":   ("T", "red",   34, 6.0, 72),
    "sw_concussion":        ("U", "ion",   40, 6.0, 72),
}

# ---------------------------------------------------------------- the guns
# gun -> (profile id, colour, flash strength 0.6..1.6, note, recoil: climb, drift, recover, maxp,
#         view back, what its round is)
# Kick is STATED. Pistols snap and come back fast; heavy guns settle slowly; rotaries are tiny per
# shot and wander as the rate builds; the concussion rifle and the cannon are the ones allowed to hit.
GUNS = [
    # ---- Wardusted
    # HAN'S GUN FIRES RED, like the film -- the owner's word that set the colours for the whole set.
    ("DL44Blaster",       "sw_dl44",      "red",   0.9, "Han's heavy blaster pistol: a sharp red snap, as in the film",
     (1.35, 0.22, 16, 5.0, 1.5), "sw_bolt_red_pistol"),
    ("E11Blaster",        "sw_e11",       "red",   0.8, "the stormtrooper rifle: light, quick, and red",
     (0.70, 0.30, 14, 4.2, 1.1), "sw_bolt_red_rifle"),
    ("DarkBlaster",       "sw_darkblaster", "red", 1.05, "a dark trooper's blaster: heavier bolts",
     (1.05, 0.32, 18, 5.0, 1.4), "sw_bolt_red_heavy"),
    ("DLT19",             "sw_dlt19",     "red",   0.95, "a heavy repeating blaster: small per shot, builds with the rate",
     (0.42, 0.36, 22, 4.6, 0.9), "sw_bolt_red_heavy"),
    ("E22Blaster",        "sw_e22",       "red",   1.0, "twin barrels: a double snap and a shove",
     (0.85, 0.30, 16, 4.8, 1.3), "sw_bolt_red_rifle"),
    ("Z6RotaryBlaster",   "sw_z6",        "blue",  0.85, "a rotary cannon: tiny per shot, and it wanders as it spins",
     (0.26, 0.55, 26, 4.2, 0.7), "sw_bolt_blue_heavy"),
    ("Bowcaster",         "sw_bowcaster", "green", 1.3, "a Wookiee bowcaster: a quarrel with a real shove behind it",
     (2.40, 0.30, 22, 7.0, 2.4), "sw_bolt_green_quarrel"),
    ("ConcussionRifle",   "sw_concussion_rifle", "ion", 1.5, "the thump of the set: a pulse of pressure",
     (3.30, 0.28, 26, 8.5, 3.2), "sw_concussion"),
    ("DisruptorRifle",    "sw_disruptor", "red",   1.2, "a disruptor: a hard crack and a beam, no bolt",
     (1.90, 0.18, 20, 6.2, 2.0), "sw_disruptor"),
    ("SniperRifle",       "sw_sniper",    "red",   1.1, "a long blaster: one hard crack",
     (2.10, 0.16, 20, 6.4, 2.1), "sw_bolt_red_sniper"),
    ("DarkAssaultCannon", "sw_assault_cannon", "red", 1.6, "the heaviest thing in the set: it settles slowly",
     (3.60, 0.42, 30, 9.0, 3.6), "sw_bolt_red_charge"),
    # ---- Xim's Star Wars Doom, on Doom's own slots
    ("XIM_Pistol",        "sw_xim_blaster", "red",   0.85, "Xim's blaster pistol",
     (1.25, 0.22, 16, 4.8, 1.4), "sw_bolt_red_pistol"),
    ("XIM_Shotgun",       "sw_xim_rifle", "red",   0.9, "Xim's blaster rifle",
     (0.80, 0.30, 15, 4.6, 1.2), "sw_bolt_red_rifle"),
    ("XIM_SuperShotgun",  "sw_xim_ion",   "ion",   1.15, "Xim's ion blaster: a sharp blue-white crack",
     (1.60, 0.24, 18, 5.6, 1.8), "sw_bolt_ion"),
    ("XIM_Chaingun",      "sw_xim_heavy", "red",   0.95, "Xim's heavy blaster: builds with the rate",
     (0.45, 0.36, 22, 4.6, 0.9), "sw_bolt_red_heavy"),
    ("XIM_RocketLauncher", "sw_xim_bowcaster", "green", 1.3, "Xim's bowcaster",
     (2.40, 0.30, 22, 7.0, 2.4), "sw_bolt_green_quarrel"),
    ("XIM_PlasmaRifle",   "sw_xim_rotary", "blue",  0.85, "Xim's rotary blaster: wanders as it spins",
     (0.28, 0.55, 26, 4.2, 0.7), "sw_bolt_blue_heavy"),
]

# Thrown and planted things: no muzzle, so no flash and no kick -- STATED, not omitted. They name the
# impact in their own class when they go off, the way the thrown lighter does.
THROWN = [
    ("RebelThermalDetonator", "sw_thermal"),
    ("ProximityMines",        "sw_mine"),
    ("XIM_BFG",               "sw_thermal_big"),
]

SABER = [("blue", (110, 165, 255)), ("green", (90, 255, 110)), ("red", (255, 55, 45)),
         ("purple", (190, 90, 255)), ("yellow", (255, 225, 80)), ("orange", (255, 140, 40)),
         ("cyan", (80, 245, 255)), ("white", (235, 240, 255))]


def rgb(c):
    return "%d, %d, %d" % c


def bursts_for_colour(name, c):
    """The coloured sparks and glows everything else is built from. Tinted from the default particle
    the way energy_sparks_plasma is, so no new art and no borrowed art."""
    return [
        "burst %s_snap   # a %s muzzle snap: a short hard spray of coloured light" % (name, name.split("_")[-1]),
        "  count   = 9", "  cone    = 22", "  speed   = 190, 0.5", "  life    = 0.07, 0.3",
        "  color   = %s" % rgb(c), "  glow    = 3.6", "  size    = 0.9, 0.3", "  drag    = 3.0",
        "  orient  = streak", "  stretch = 0.02", "  aim     = along", "end", "",
        "burst %s_spark   # coloured sparks off whatever it struck" % name,
        "  count   = 16", "  cone    = 64", "  speed   = 240, 0.55", "  life    = 0.24, 0.4",
        "  color   = %s" % rgb(c), "  glow    = 2.6", "  size    = 0.6, 0.3", "  drag    = 2.2",
        "  orient  = streak", "  stretch = 0.03", "end", "",
        "burst %s_glow   # the flash of the hit itself: a soft ball of its own colour, gone at once" % name,
        "  count   = 2", "  cone    = 0", "  speed   = 0, 0", "  life    = 0.10, 0.25",
        "  color   = %s" % rgb(c), "  glow    = 4.0", "  size    = 3.2, 0.3", "end", "",
    ]


def bolt_impacts(colour, c):
    n = "sw_bolt_%s" % colour
    b = "swb_%s" % colour
    return [
        "# A %s BOLT LANDING: a flash of its own colour lighting the wall, sparks, a scorch, and smoke off" % colour.upper(),
        "# the burnt spot. That smoke is the hit burning, not powder, which is why it is allowed.",
        "impact %s   # a %s bolt on stone: flash, sparks, scorch, smoke" % (n, colour),
        "  bursts     = %s_glow, %s_spark, flame_smoke, dust_concrete" % (b, b),
        "  maybe      = spark_hot 0.5, plasma_ozone 0.4",
        "  mark       = ring, 6, 110",
        "  markcolor  = 38, 30, 28",
        "  light      = 115, 2.4, 5",
        "  lightcolor = %s" % rgb(c),
        "  smokevolume = 10, 0.3, 0.9",
        "  damage     = scorch_ring, 6, 0.15, 0.55, 0.45",
        "  sound      = rsb/impact/electric",
        "end", "",
        "impact %s.metal   # on metal it sparks harder and leaves a hotter mark" % n,
        "  bursts     = %s_glow, %s_spark, spark_metal, flame_smoke" % (b, b),
        "  maybe      = ember_metal 0.5",
        "  mark       = ring, 6, 140",
        "  markcolor  = 60, 40, 30",
        "  light      = 125, 2.6, 5",
        "  lightcolor = %s" % rgb(c),
        "  damage     = scorch_ring, 6, 0.12, 0.6, 0.6",
        "  sound      = rsb/impact/electric",
        "end", "",
        "impact %s.flesh   # CAUTERISED, not a bullet wound: a flash, a sizzle, steam and char, no blood spray" % n,
        "  bursts     = %s_glow, flesh_cook_steam" % b,
        "  maybe      = flesh_char_flecks 0.6, %s_spark 0.4" % b,
        "  light      = 90, 2.0, 4",
        "  lightcolor = %s" % rgb(c),
        "  sound      = none",
        "end", "",
        "impact %s.liquid   # into water: it hisses out in a puff of steam" % n,
        "  bursts     = %s_glow, splash_liquid, flesh_cook_steam" % b,
        "  light      = 70, 1.4, 4",
        "  lightcolor = %s" % rgb(c),
        "  sound      = rsb/flame/hiss1",
        "end", "",
    ]


def saber_blocks(colour, c):
    s = "saber_%s" % colour
    b = "swb_saber_%s" % colour
    return bursts_for_colour("swb_saber_%s" % colour, c) + [
        "# ---- THE %s BLADE" % colour.upper(),
        "impact saber_deflect_%s   # a bolt snapped off the blade: a flare of the blade's colour, white sparks, arcs" % colour,
        "  bursts     = %s_glow, %s_spark, spark_hot, arcs_electric" % (b, b),
        "  maybe      = energy_sparks_plasma 0.6",
        "  light      = 170, 3.0, 5",
        "  lightcolor = %s" % rgb(c),
        "  sound      = none",
        "end", "",
        "impact saber_hit_%s   # a strike through a body: cauterised on the way through" % colour,
        "  bursts     = %s_glow, flesh_cook_steam, flesh_char_flecks" % b,
        "  maybe      = %s_spark 0.5" % b,
        "  light      = 120, 2.2, 4",
        "  lightcolor = %s" % rgb(c),
        "  sound      = none",
        "end", "",
        "# THE BLADE IN A WALL. Each tic it is held there feeds one molten spot, which DRAGS WITH THE",
        "# BLADE and lays a glowing groove along the way it was swept, then cools once the blade leaves --",
        "# the blast door. The glow is heat, so it is orange-white whatever the blade's colour; the",
        "# sparks and the flash where it bites are the blade's own.",
        "impact saber_wall_%s   # the blade biting into a wall" % colour,
        "  bursts     = %s_spark, spark_hot" % b,
        "  maybe      = melt_embers 0.5",
        "  light      = 110, 2.2, 3",
        "  lightcolor = %s" % rgb(c),
        "  hotspot    = saber_melt",
        "  sound      = none",
        "end", "",
        "trail saber_smear_%s   # the swing: a ribbon of the blade's light, gone in a moment" % colour,
        "  line        = 1.3, 4.0, 1.5, 6",
        "  linecolor   = %s" % rgb(c),
        "  linelook    = 0.6, 2.4",
        "end", "",
        "impact saber_clash_%s   # blade on blade: a white flare with the blade's colour round it" % colour,
        "  bursts     = %s_glow, %s_spark, spark_hot, spk_stars, arcs_electric" % (b, b),
        "  maybe      = energy_sparks_plasma 0.7",
        "  light      = 220, 3.6, 6",
        "  lightcolor = %s" % rgb(c),
        "  sound      = none",
        "end", "",
    ]


def blocks():
    out = [BEGIN, ""]
    for colour, c in BOLT.items():
        out += bursts_for_colour("swb_%s" % colour, c)
    for colour, c in BOLT.items():
        out += bolt_impacts(colour, c)

    # ---- the special impacts
    out += [
        "# THE DISRUPTOR: nothing flies. A beam is laid muzzle to hit and what it hit FLAKES -- embers",
        "# and ash lifting off, not a scorch. It is the one weapon in the set that should look wrong.",
        "trail sw_disruptor   # a disruptor beam: a white core, a hot red edge, gone in a moment",
        "  line        = 0.8, 3.0, 2.8, 12",
        "  linecolor   = 255, 110, 80",
        "  linelook    = 0.5, 2.2",
        "  lights      = 3, 80, 1.8, 3",
        "  lightcolor  = 255, 90, 60",
        "end", "",
        "impact sw_disrupt   # disintegration: embers and ash lifting off where it struck",
        "  bursts     = melt_embers, flesh_char_flecks, flame_smoke, swb_red_glow",
        "  maybe      = flame_embers_rise 0.7",
        "  mark       = ring, 7, 160",
        "  markcolor  = 30, 22, 20",
        "  light      = 130, 2.6, 6",
        "  lightcolor = 255, 110, 70",
        "  damage     = scorch_ring, 7, 0.2, 0.7, 0.5",
        "  sound      = rsb/flame/hiss2",
        "end", "",
        "# THE CONCUSSION RIFLE: a pulse of pressure. What sells it is the air bending outward where it",
        "# lands and the room shoving back -- the thump of the set, and nothing like a bolt.",
        "impact sw_concussion   # a concussion blast: a ring of bent air, dust thrown off the walls, a thump",
        "  bursts     = swb_ion_glow, dust_bloom_concrete, chips_concrete, rubble_concrete",
        "  maybe      = dust_jet_concrete 0.7",
        "  mark       = ring, 16, 200",
        "  markcolor  = 40, 36, 34",
        "  light      = 180, 3.0, 6",
        "  lightcolor = 185, 228, 255",
        "  smokevolume = 26, 0.6, 0.5",
        "  damage     = crater, 14, 0.4, 0.5, 0",
        "  ripple     = 180, 1.2, 16, 0, 0.3",
        "  sound      = rsb/impact/concrete",
        "  tail       = rsb/blast/roll, 0.7",
        "end", "",
        "# THE ASSAULT CANNON'S CHARGE: a slow fat blob that lands like a small bomb.",
        "impact sw_charge   # a heavy charge landing: a red flash, a spray of sparks, a scorched crater",
        "  bursts     = swb_red_glow, swb_red_spark, spark_hot, flame_smoke, dust_bloom_concrete",
        "  maybe      = plasma_ozone 0.6, chips_concrete 0.6",
        "  mark       = ring, 12, 180",
        "  markcolor  = 36, 28, 26",
        "  light      = 190, 3.2, 6",
        "  lightcolor = 255, 70, 50",
        "  smokevolume = 18, 0.5, 1.0",
        "  damage     = crater, 10, 0.35, 0.8, 0.5",
        "  ripple     = 120, 0.8, 12, 0, 0.15",
        "  sound      = rsb/impact/electric",
        "end", "",
        "# A THERMAL DETONATOR IS NOT A GRENADE. No fireball and no soot: a white-blue flash of energy,",
        "# a ring of bent air, and everything near it thrown outward.",
        "impact sw_thermal   # a thermal detonator: a white-blue flash, a ring of pressure, sparks",
        "  bursts     = flashbang_core, swb_ion_glow, energy_sparks_plasma, dust_bloom_concrete",
        "  maybe      = rubble_concrete 0.6, arcs_electric 0.6",
        "  mark       = ring, 22, 220",
        "  markcolor  = 34, 30, 30",
        "  light      = 300, 4.0, 8",
        "  lightcolor = 200, 230, 255",
        "  smokevolume = 30, 0.6, 1.2",
        "  damage     = crater, 20, 0.5, 0.7, 0",
        "  ripple     = 230, 1.4, 18, 0, 0.35",
        "  sound      = rsb/impact/concrete",
        "  tail       = rsb/blast/roll, 1.0",
        "end", "",
        "impact sw_thermal_big   # Xim's thermal detonators on the BFG slot: the same thing, much bigger",
        "  bursts     = flashbang_core, swb_ion_glow, energy_sparks_plasma, dust_bloom_concrete, rubble_concrete",
        "  maybe      = arcs_electric 0.8",
        "  mark       = ring, 34, 260",
        "  markcolor  = 32, 28, 28",
        "  light      = 420, 4.8, 10",
        "  lightcolor = 200, 230, 255",
        "  smokevolume = 44, 0.8, 1.4",
        "  damage     = crater, 30, 0.6, 0.8, 0",
        "  ripple     = 320, 1.6, 22, 0, 0.45",
        "  sound      = rsb/impact/concrete",
        "  tail       = rsb/blast/roll, 1.0",   # a volume, so 0..1 -- the size is in the light and the ripple
        "end", "",
        "impact sw_mine   # a proximity mine: smaller and sharper than a detonator",
        "  bursts     = flashbang_core, swb_ion_glow, energy_sparks_plasma, dust_bloom_concrete",
        "  mark       = ring, 16, 200",
        "  markcolor  = 34, 30, 30",
        "  light      = 240, 3.6, 7",
        "  lightcolor = 200, 230, 255",
        "  damage     = crater, 14, 0.4, 0.6, 0",
        "  ripple     = 180, 1.2, 14, 0, 0.3",
        "  sound      = rsb/impact/concrete",
        "  tail       = rsb/blast/roll, 0.8",
        "end", "",
    ]

    # ---- rounds
    for rid, (frame, colour, speed, radius, whiz) in ROUNDS.items():
        c = BOLT[colour]
        impact = ("sw_concussion" if rid == "sw_concussion" else
                  "sw_charge" if rid == "sw_bolt_red_charge" else
                  "sw_bolt_%s" % colour)
        out += [
            "ballistics %s   # %s" % (rid, FRAMES[frame][3]),
            "  speed  = %d" % speed,
            "  radius = %.1f" % radius,
            "  damage = none",
            "end", "",
            "roundlook %s" % rid,
            "  look      = model, RSBM%s" % frame,
            "  glide     = yes",
            "  wake      = none",
            "  impact    = %s" % impact,
            "  whiz      = %d, rsb/whiz" % whiz,
            # IT LIGHTS THE WALLS IT PASSES -- the single thing that makes a bolt a bolt.
            "  light     = %d, %.1f" % (80 if "pistol" in rid else 110 if "heavy" in rid or "charge" in rid else 95,
                                        2.0 if "pistol" in rid else 2.4),
            "  lightcolor = %s" % rgb(c),
            "  lightlook = streak",
            "end", "",
            "round %s" % rid,
            "  ballistics = %s" % rid,
            "  roundlook  = %s" % rid,
            "end", "",
        ]
    # the disruptor: an invisible round that lays its own beam
    out += [
        "ballistics sw_disruptor   # a disruptor: nothing flies you could see",
        "  speed  = 400",
        "  radius = 2.0",
        "  damage = none",
        "end", "",
        "roundlook sw_disruptor",
        "  look      = none",
        "  glide     = yes",
        "  trail     = sw_disruptor",
        "  impact    = sw_disrupt",
        "end", "",
        "round sw_disruptor",
        "  ballistics = sw_disruptor",
        "  roundlook  = sw_disruptor",
        "end", "",
    ]

    # ---- flashes and recoil, per gun
    flashes = []
    for cls, pid, colour, s, note, rc, rnd in GUNS:
        c = BOLT[colour]
        climb, drift, recover, maxp, viewback = rc
        flashes += [
            "# %s -- a blaster flash: a coloured snap of light and a whiff of ozone. No flame card, no" % cls,
            "# powder smoke, no petals: STAR WARS, NOT JOHN WICK.",
            "flash %s   # %s" % (pid, note),
            "  light      = %d, %.1f, 2" % (int(120 + 90 * s), 2.2 + 1.2 * s),
            "  lightcolor = %s" % rgb(c),
            "  cone       = %d, %d, %d, 5" % (int(8 + 8 * s), int(20 + 22 * s), int(36 + 40 * s)),
            "  conetics   = 2",
            "  bursts     = swb_%s_snap, swb_%s_glow" % (colour, colour),
            "  maybe      = plasma_ozone 0.5",
            "  flame      = 0.0",
            "  smoke      = 0, 0.0, 0.0",
            "end", "",
        ]
        out += [
            "recoil %s   # %s -- STATED: an energy weapon has no cartridge, and no kick is the one wrong answer" % (pid, note),
            "  climb   = %.2f" % climb,
            "  drift   = %.2f, 5" % drift,
            "  recover = %d, 6" % recover,
            "  max     = %.1f, %.1f" % (maxp, max(2.0, maxp * 0.45)),
            "  bloom   = 0.00",
            "  brace   = 0.6, 0.85",
            "  view    = %.1f, %d, 1, %d" % (viewback, 4 + int(3 * viewback / 2.0), 6),
            "end", "",
        ]
    out += flashes

    # ---- the saber
    out += ["", "# ================================ THE LIGHTSABER ================================", "",
            "# ONE MOLTEN SPOT, SHARED BY EVERY BLADE COLOUR: melting is HEAT, so it glows orange-white",
            "# whatever colour cut it. Fed every tic the blade is in the wall; it drags with the blade and",
            "# lays its groove ALONG THE SWEEP (`damage ... travel`), then cools once the blade is gone.",
            "hotspot saber_melt   # a blade held in a wall: a glowing groove that follows it, and cools",
            "  merge      = 18",
            "  heat       = 0.35, 0.9, 1.4",
            "  bursts     = melt_embers 6, spark_hot 10, flame_smoke 4, spark_spray 3",
            "  light      = 90, 2.0",
            "  lightcolor = 255, 170, 90",
            "  mark       = gouge, 2.5, 8, 7, 90",
            "  markcolor  = 255, 150, 70",
            "  shimmer    = 10, 0.8",
            "  sound      = none",
            "  smokevolume = 10, 0.35, 0.6",
            "  damage     = melt, 2.5, 6, 0.8, 0.05, 0.6, travel",
            "end", ""]
    for colour, c in SABER:
        out += saber_blocks(colour, c)

    # ---- light -> extreme, through the shared transformer
    sys.path.insert(0, HERE)
    import gen_ww2_profiles as WW2
    out += ["# LIGHT -> EXTREME: every flash again, as MORE of what it is -- through the WW2 set's own",
            "# transformer, so this set grows the same way as the other ten.", ""]
    out += WW2.extreme_blocks(flashes)
    out += ["", END, ""]
    return out



# ---------------------------------------------------------------- enemy fire, for the Xim pack only
# XIM'S STORMTROOPERS ARE DOOM'S ZOMBIEMEN, reskinned by DeHackEd, and RS_Ballistics turns their
# hitscans into real rounds -- which fly as orange bullets unless something says otherwise. This is
# that something: the three enemy round looks redefined as red bolts.
#
# IT IS AN OVERRIDE LUMP, NOT PART OF RS_BALLISTICS, and that is the point. Any loaded pack's RSBDEFS
# replaces a profile of the same name, so it goes INSIDE the Xim REMA pack: load Xim and the troopers
# fire red bolts; load plain Doom and zombiemen fire bullets as before. Nothing detects anything.
#
# LOOKS ONLY. Enemy rounds already fly at 80 units a tic, which is bolt speed, so the gameplay is
# untouched -- no shot becomes easier to dodge than it was yesterday.
ENEMIES_OUT = os.path.join(PKG, "_staged", "RSBDEFS.xim_enemies")


def enemy_override():
    red = rgb(BOLT["red"])
    lines = [
        "# ============================================================================",
        "# XIM'S TROOPERS FIRE RED BOLTS. Ship this as RSBDEFS inside the Xim REMA pack.",
        "# Generated by RS_Ballistics tools/gen_starwars_profiles.py --enemies -- do not hand-edit.",
        "# It replaces three RS_Ballistics round looks by name, only while this pack is loaded.",
        "# ============================================================================",
        "",
    ]
    for name, frame, note in [("enemy_round", "J", "a trooper's blaster bolt"),
                              ("enemy_pellet", "I", "a spread of smaller bolts"),
                              ("enemy_heavy", "K", "a heavy repeater's bolt")]:
        lines += [
            "roundlook %s   # %s: red, as every hand blaster in the films" % (name, note),
            "  look       = model, RSBM%s" % frame,
            "  glide      = yes",
            "  wake       = none",
            "  impact     = sw_bolt_red",
            "  whiz       = 60, rsb/whiz",
            "  light      = %d, 2.2" % (110 if name == "enemy_heavy" else 90),
            "  lightcolor = %s" % red,
            "  lightlook  = streak",
            "end", "",
        ]
    return lines

def check_sounds(body):
    declared = set()
    for line in io.open(SND, encoding="utf-8", errors="replace"):
        t = line.split("//")[0].strip()
        for kw in ("$random", "$alias", "$playersound", "$limit", "$pitchset", "$volume"):
            if t.lower().startswith(kw):
                t = t[len(kw):].strip()
                break
        m = re.match(r"^([A-Za-z0-9_/\-]+)", t)
        if m:
            declared.add(m.group(1).lower())
    bad = []
    for ln in body:
        m = re.match(r"^\s*(sound|tail|whiz)\s*=\s*(?:\d+\s*,\s*)?([A-Za-z0-9_/\-]+)", ln)
        if not m:
            continue
        n = m.group(2).lower()
        if n in ("none", "") or n in declared or (n + "/int") in declared or (n + "/ext") in declared:
            continue
        bad.append(m.group(2))
    if bad:
        raise SystemExit("REFUSING TO WRITE: not declared in SNDINFO, would be silent:\n  "
                         + "\n  ".join(sorted(set(bad))))


def skins():
    """Recolour btracer.png: the white-hot core kept, the orange edge swapped for each bolt colour.
    GENERATED from this package's own texture -- no new art and nothing borrowed."""
    from PIL import Image
    src = Image.open(os.path.join(PKG, "models", "bullet", "btracer.png")).convert("RGBA")
    for colour, (r, g, b) in BOLT.items():
        im = src.copy()
        px = im.load()
        w, h = im.size
        for y in range(h):
            for x in range(w):
                pr, pg, pb, pa = px[x, y]
                if pa == 0:
                    continue
                white = min(pr, pg, pb) / 255.0       # how much of this pixel is the hot core
                bright = max(pr, pg, pb) / 255.0
                nr = int(255 * white + r * bright * (1 - white))
                ng = int(255 * white + g * bright * (1 - white))
                nb = int(255 * white + b * bright * (1 - white))
                px[x, y] = (min(255, nr), min(255, ng), min(255, nb), pa)
        im.save(os.path.join(PKG, "models", "bullet", "bolt_%s.png" % colour))


def modeldef():
    lines = [MD_BEGIN, "//",
             "// STAR WARS BOLTS: the same round-in-flight mesh as every bullet here, in a coloured skin",
             "// generated from its own texture (tools/gen_starwars_profiles.py), at its own size. Frames",
             "// I..U of RSBM, on BOTH round classes -- MODELDEF does not follow inheritance.", "//"]
    for cls in ("RSB_Bullet", "RSB_EnemyBullet"):
        for f, (colour, ln, wd, note) in FRAMES.items():
            lines += ["", "Model %s   // %s" % (cls, note), "{",
                      '\tPath "models/bullet"', '\tModel 0 "btracer.obj"',
                      '\tSurfaceSkin 0 0 "bolt_%s.png"' % colour,
                      "\tScale %.4f %.4f %.4f" % (ln / 80.0, wd / 7.0, wd / 7.0),
                      "\tDontCullBackfaces", "\tUSEACTORPITCH", "\tUSEACTORROLL",
                      "\tFrameIndex RSBM %s 0 0" % f, "}"]
    lines += ["", MD_END]
    return lines


def sheet():
    print("SHEET KEYS FOR THE WEAPONS LANE -- Star Wars\n")
    for cls, pid, colour, s, note, rc, rnd in GUNS:
        print('gun "%s"   # %s' % (cls, note))
        print('  flashprofile         = "%s"' % pid)
        print('  recoilprofile        = "%s"' % pid)
        print('  roundprofile         = "%s"' % rnd)
        print('  ejectaprofile        = "none"')
        print()
    for cls, imp in THROWN:
        print('gun "%s"' % cls)
        print('  flashprofile         = "none"')
        print('  recoilprofile        = "none"')
        print('  ejectaprofile        = "none"')
        print('  # THROWN: no round in flight -- the class names the impact where it goes off:')
        print('  #   RSB_Impact.Land(self, "%s", vel)' % imp)
        print()
    print("THE LIGHTSABER -- `colour` is lower case from the saber's own table:")
    print("  deflect   \"saber_deflect_\" .. colour  where deflect_energy / deflect_bullet are named now")
    print("  cut       RSB_Impact.At(owner, point, dir, \"saber_hit_\" .. colour, mo)   in Cut(), on each hit")
    print("  wall      trace the blade line; on a hit:")
    print("            RSB_Impact.LandOn(owner, RSB_Materials.FromTrace(d, dir), \"saber_wall_\" .. colour, dir)")
    print("  smear     while the tip is fast: RSB_Trail.Lay(\"saber_smear_\" .. colour, owner, lastTip, tip)")
    print("  clash     \"saber_clash_\" .. colour")


def main():
    if "--sheet" in sys.argv:
        sheet()
        return
    if "--enemies" in sys.argv:
        body = enemy_override()
        check_sounds(body)
        io.open(ENEMIES_OUT, "w", encoding="utf-8", newline="").write("\r\n".join(body) + "\r\n")
        print("wrote %s -- ship it as RSBDEFS inside the Xim REMA pack" % ENEMIES_OUT)
        return
    skins()
    body = blocks()
    check_sounds(body)
    text = io.open(DEFS, encoding="utf-8", newline="").read()
    nl = "\r\n" if "\r\n" in text else "\n"
    if BEGIN in text:
        i, j = text.index(BEGIN), text.index(END) + len(END) + len(nl)
        text = text[:i] + text[j:]
    anchor = "# ---- END NEW SETS"
    if anchor not in text:
        raise SystemExit("no anchor")
    text = text.replace(anchor, nl.join(body) + anchor, 1)
    io.open(DEFS, "w", encoding="utf-8", newline="").write(text)

    md = io.open(MODELDEF, encoding="utf-8", newline="").read()
    mnl = "\r\n" if "\r\n" in md else "\n"
    if MD_BEGIN in md:
        i, j = md.index(MD_BEGIN), md.index(MD_END) + len(MD_END)
        md = md[:i].rstrip() + md[j:]
    md = md.rstrip() + mnl + mnl + mnl.join(modeldef()) + mnl
    io.open(MODELDEF, "w", encoding="utf-8", newline="").write(md)

    from PIL import Image
    for f in FRAMES:
        Image.new("RGBA", (1, 1), (0, 0, 0, 0)).save(os.path.join(PKG, "sprites", "RSBM%s0.png" % f))

    n = len([l for l in body if re.match(r"^(flash|recoil|impact|burst|ballistics|roundlook|round|trail|hotspot) ", l)])
    print("%d Star Wars profiles, %d bolt frames, %d skins" % (n, len(FRAMES), len(BOLT)))


if __name__ == "__main__":
    main()
