#!/usr/bin/env python3
"""
gen_lastsets_profiles.py -- Robocop and HacX, the last two sets in someone else's clothes.

Fourteen guns, and the coverage checker now names them exactly: seven and seven, every one naming a
profile from Vanilla, Vanilla+ or the house. The owner: think about the kind of gun each one is.

SO THE POINT OF THIS FILE IS THE THINKING, not the arithmetic. The arithmetic is the same free-recoil
formula every other set uses, off the baseweights already on their sheets. What differs is that these
two sets contain guns with a CHARACTER nothing in the package has drawn yet:

  RC_Auto9      a compensated machine pistol. The compensator is the whole gun -- it vents UP and
                SIDEWAYS, so the flash is wide and flat, and seventeen rounds a second climbs LESS
                than a bare 9mm would. Ports, not a plume.
  RC_Cobra      an anti-materiel cannon that blows up a car. The most violent thing in either set,
                and it has to read as artillery rather than as a big rocket launcher.
  RC_M32        a six-shot REVOLVER grenade launcher: a soft low-velocity thump, a lot of smoke, and
                fast enough to walk shots across a room, which no other launcher here can do.
  HX_Tazer      ELECTRIC, and it has been wearing a plasma flash. Arcs and coils, not a glow.
  HX_Cryogun    COLD, and every single effect in this package is hot. Frost needs its own vocabulary:
                white vapour that FALLS, ice that sublimates rather than burns, a pale mark. This is
                the one real new thing here.
  HX_Nuker      a nuke in a cyberpunk shed. Bigger than the BFG and cruder.

LIGHT -> EXTREME. Every flash gets its @extreme twin through the shared transformer, so each gun is
MORE of what it is at the top setting rather than a different gun -- the rule that stopped the
suppressed guns growing a cone when the owner turned everything up.

    python tools/gen_lastsets_profiles.py
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFS = os.path.join(HERE, "..", "RSBDEFS.txt")
SND = os.path.join(HERE, "..", "SNDINFO.txt")
BEGIN = "# ---- BEGIN ROBOCOP + HACX (generated by tools/gen_lastsets_profiles.py) ----"
END = "# ---- END ROBOCOP + HACX ----"

CLIMB_PER_FPS = 0.148
CLIMB_CEILING = 4.2
ACTION = {"bolt": 1.55, "break": 1.50, "pump": 1.45, "revolver": 1.20, "semi": 1.15,
          "auto": 0.85, "belt": 0.45, "harness": 0.25}

# gun -> bullet grains, muzzle fps, charge grains, EMPTY lb (their sheet), capacity, round grains,
#        action, note
DERIVED = {
    # ---- ROBOCOP. Real guns, real weights, and the Auto 9 is the one with a personality.
    "rc_auto9":    (115, 1250, 5.0, 2.30, 15, 190, "auto",
                    "the Auto 9: a machine pistol with a compensator longer than the slide"),
    "rc_m27":      (62, 3020, 25.0, 7.19, 30, 190, "auto", "an M16-class 5.56 service rifle"),
    "rc_ksg":      (437, 1325, 32.0, 7.01, 12, 694, "pump", "a bullpup 12 gauge"),
    "rc_shotgun":  (437, 1325, 32.0, 5.71, 5, 694, "pump",
                    "a LIGHT pump gun -- five and a half pounds, so it kicks harder than the bullpup"),
    "rc_m32":      (3550, 250, 5.0, 6.50, 6, 1400, "revolver",
                    "a six-shot revolver grenade launcher: 230 g at 250 fps, a shove not a snap"),
    "rc_chaingun": (147, 2750, 46.0, 25.00, 100, 370, "belt", "a 7.62 belt gun on a 25 lb mount"),
    # ---- HACX
    "hx_pistol":   (115, 1150, 4.5, 1.97, 15, 190, "semi", "a light 9mm sidearm"),
    "hx_uzi":      (115, 1250, 6.0, 6.13, 32, 190, "auto", "an Uzi: heavy for the round, so it is steady"),
}

# The ones with no cartridge at all: stated, because inventing a load so the arithmetic would run is
# the false precision this package refuses. climb, drift, period, recover, delay, maxp, maxy, note
STATED = {
    "rc_cobra":    (3.60, 0.45, 4, 26, 9, 9.0, 4.0,
                    "the Cobra Assault Cannon: it blows up a car. Artillery, not a rocket launcher"),
    "hx_tazer":    (0.55, 0.20, 7, 12, 4, 3.6, 2.0, "a taser: the snap is electrical, not recoil"),
    "hx_cryogun":  (0.70, 0.16, 9, 14, 5, 3.8, 2.0, "a cryo jet: pressure, and it pushes steadily"),
    "hx_reznator": (0.95, 0.22, 6, 13, 4, 4.2, 2.2, "HacX's energy rifle"),
    "hx_zooka":    (2.60, 0.40, 5, 20, 7, 7.5, 3.5, "a home-made rocket tube"),
    "hx_nuker":    (2.90, 0.25, 3, 30, 12, 8.0, 3.5, "a nuke built in a shed"),
}


def free_recoil(wb, vb, wc, lb):
    vg = (wb * vb + 4700.0 * wc) / (7000.0 * lb)
    return vg, lb * vg * vg / 64.348, lb * vg / 32.174


def recoil_blocks():
    out = []
    for gid in DERIVED:
        wb, vb, wc, empty, cap, rgr, action, note = DERIVED[gid]
        loaded = empty + cap * (rgr / 7000.0)
        vg, e, imp = free_recoil(wb, vb, wc, loaded)
        climb = min(CLIMB_CEILING, vg * CLIMB_PER_FPS * ACTION[action])
        # THE COMPENSATOR. A brake vents gas up and sideways and takes a real bite out of muzzle rise
        # -- that is what it is FOR, and on the Auto 9 it is most of the gun. This is the only place
        # in the package where a mechanical feature, not a mass, changes the kick, so it is stated
        # here with its reason rather than folded into a fudged action multiplier.
        brake = 0.62 if gid == "rc_auto9" else 1.0
        climb *= brake
        out += ["recoil %s   # %s -- %.1f ft-lb, Vg %.2f fps, impulse %.3f lb-s%s"
                % (gid, note, e, vg, imp, ", compensator takes 38%" if brake < 1 else ""),
                "  climb   = %.2f" % climb,
                "  shot    = %.2f, %.1f, %.3f" % (vg, e, imp),
                "  drift   = %.2f, %d" % (0.30 if action != "belt" else 0.22, 5),
                "  recover = %d, %d" % (int(max(8, min(30, 26 * (3.0 / max(1.0, climb)) ** 0.3))), 6),
                "  max     = %.1f, %.1f" % (max(3.0, min(10.0, 3.0 + 2.2 * climb)),
                                            max(2.0, 1.0 + 1.1 * climb)),
                "  bloom   = 0.02",
                "  brace   = 0.6, 0.85",
                "  view    = %.1f, %d, 1, %d" % (1.0 + 1.2 * (climb / 2.6),
                                                 4 + int(4 * (climb / 2.6)), 6),
                "end", ""]
    for gid in STATED:
        climb, drift, period, rec, delay, maxp, maxy, note = STATED[gid]
        out += ["recoil %s   # %s -- STATED: no cartridge to derive from" % (gid, note),
                "  climb   = %.2f" % climb,
                "  drift   = %.2f, %d" % (drift, period),
                "  recover = %d, %d" % (rec, delay),
                "  max     = %.1f, %.1f" % (maxp, maxy),
                "  bloom   = 0.00",
                "  brace   = 0.6, 0.85",
                "  view    = %.1f, %d, 1, %d" % (1.0 + 1.2 * (climb / 2.6),
                                                 4 + int(4 * (climb / 2.6)), 8),
                "end", ""]
    return out


def cold_blocks():
    """COLD, which this package has never drawn. Every effect in it is hot -- fire rises, embers
    glow, smoke lifts while it is warm and stops when it cools. Frost does the opposite of all of
    that: the vapour is heavier than air and FALLS, the crystals do not burn out, they sublimate,
    and the light it throws is a pale reflection rather than an emission. So it gets its own bursts
    rather than a blue-tinted flame."""
    return [
        "# COLD VAPOUR: heavier than air, so it has POSITIVE gravity and pools rather than rising.",
        "# That one sign is most of what makes it read as cold instead of as blue smoke.",
        "burst cryo_fog            # the breath of a cryo jet, sinking",
        "  count    = 5",
        "  cone     = 26",
        "  speed    = 90, 0.5",
        "  life     = 1.6, 0.35",
        "  size     = 1.9, 0.5",
        "  gravity  = 0.22",
        "  drag     = 0.26",
        "  color    = 224, 240, 252",
        "  particle = rsb_smoke_gun",
        "end",
        "",
        "burst cryo_shards         # ice thrown off what it touches: small, bright, and they fall",
        "  count    = 7",
        "  cone     = 52",
        "  speed    = 190, 0.6",
        "  life     = 0.85, 0.3",
        "  size     = 0.5, 0.4",
        "  glow     = 0.35",
        "  gravity  = 0.9",
        "  drag     = 0.1",
        "  color    = 206, 238, 255",
        "  particle = rsb_smoke_gun",
        "end",
        "",
        "burst cryo_bloom          # the flash of freezing at the muzzle: a pale ring, gone at once",
        "  count    = 4",
        "  cone     = 74",
        "  speed    = 130, 0.5",
        "  life     = 0.45, 0.25",
        "  size     = 2.4, 0.4",
        "  glow     = 0.5",
        "  gravity  = 0.08",
        "  drag     = 0.34",
        "  color    = 236, 248, 255",
        "  particle = rsb_smoke_gun",
        "end",
        "",
        "# WHAT A FROZEN WALL LOOKS LIKE. A pale mark instead of a scorch, crystals that keep falling",
        "# after the shot, and NO heat shimmer -- the one impact in the package that bends no air.",
        "impact hx_cryo            # frost, and it creeps outward for a moment",
        "  bursts     = cryo_bloom, cryo_shards, cryo_fog",
        "  mark       = ring, 10, 240",
        "  markcolor  = 214, 240, 255",
        "  light      = 60, 0.9, 6",
        "  lightcolor = 198, 232, 255",
        "  sound      = rsb/impact/concrete",
        "end",
        "",
        "impact hx_cryo.metal      # metal takes it hardest: it goes brittle and sheds",
        "  bursts     = cryo_bloom, cryo_shards, cryo_shards, cryo_fog",
        "  mark       = ring, 11, 260",
        "  markcolor  = 220, 244, 255",
        "  light      = 66, 1.0, 6",
        "  lightcolor = 198, 232, 255",
        "  sound      = rsb/impact/metal",
        "end",
        "",
        "impact hx_cryo.liquid     # water is the one that actually freezes",
        "  bursts     = cryo_bloom, cryo_shards, splash_liquid",
        "  mark       = ring, 14, 300",
        "  markcolor  = 228, 248, 255",
        "  light      = 54, 0.8, 6",
        "  lightcolor = 198, 232, 255",
        # NO LIQUID IMPACT SOUND IS DECLARED -- the guard refused this and it was right. Concrete is
        # the nearest honest stand-in rather than a name that would be silent.
        "  sound      = rsb/impact/concrete",
        "end",
        "",
    ]


# WRITTEN FROM MEMORY, AND THE PARSER CORRECTED ALL FIVE. shockwave wants radius, strength and tics;
# groundkick names an IMPACT PROFILE and a reach, not two numbers; backblast is a tube length and a
# scale, not a list of bursts; barrelheat and barrelsmoke each take their own shape; and
# flash_brake_ring is a burst I was sure existed and does not -- spk_brake_ring does.
#
# Each of those parses as a sentence and means nothing, which is why the refusal had to come from the
# engine rather than from reading it back. Ten profiles dead on a run that said GREEN.

def flash_blocks():
    out = []

    # ---------------------------------------------------------------- ROBOCOP
    out += [
        "# THE COMPENSATOR IS THE GUN. Ports on top and the sides of a barrel longer than the frame:",
        "# the gas leaves UP and OUT rather than forward, so this is a WIDE FLAT flare with a short",
        "# cone and a ring, not a plume. Seventeen rounds a second out of two and a half pounds, and it",
        "# still climbs less than a bare 9mm, which is the whole reason the thing is bolted on.",
        "flash rc_auto9            # ported, flat and very fast",
        "  light      = 190, 3.0, 2",
        "  lightcolor = 255, 226, 178",
        "  cone       = 13, 34, 58, 4",
        "  conetics   = 2",
        "  bursts     = flash_core_9mm, flash_brake_fire, spk_brake_ring",
        "  maybe      = flash_brake_smoke 0.4, spk_streaks_fine 0.5, powder_clump 0.2",
        "  flame      = 0.07",
        "  smoke      = 2, 0.03, 0.3",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/pistol, 0.85",
        "end",
        "",
        "flash rc_m27              # a service rifle: clean, tight, unremarkable on purpose",
        "  light      = 200, 3.0, 2",
        "  lightcolor = 255, 232, 190",
        "  cone       = 16, 44, 86, 5",
        "  conetics   = 2",
        "  bursts     = flash_core, flash_petals, spk_streaks_fine",
        "  maybe      = flash_powder 0.35, spk_specks 0.35",
        "  flame      = 0.08",
        "  smoke      = 2, 0.03, 0.32",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/ar, 0.9",
        "end",
        "",
        "# A BULLPUP PUTS THE BREECH BEHIND YOUR HANDS AND THE MUZZLE A LONG WAY IN FRONT. The flash is",
        "# further out than any other shotgun here, which is a card fact rather than mine -- but the",
        "# heavier gun does mean a calmer gout than the little pump below it.",
        "flash rc_ksg              # a bullpup 12 gauge",
        "  light      = 250, 3.3, 3",
        "  lightcolor = 255, 218, 164",
        "  cone       = 26, 68, 124, 6",
        "  conetics   = 3",
        "  bursts     = flash_core, flash_petals_wide, flash_plume_wide, flash_powder",
        "  maybe      = flash_embers 0.45, flash_soot 0.4, spk_specks_wide 0.35",
        "  flame      = 0.18",
        "  smoke      = 4, 0.05, 0.55",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/shotgun, 1.0",
        "end",
        "",
        "flash rc_shotgun          # five and a half pounds of pump gun: the same shell, more of it felt",
        "  light      = 240, 3.2, 3",
        "  lightcolor = 255, 216, 160",
        "  cone       = 28, 72, 132, 6",
        "  conetics   = 3",
        "  bursts     = flash_core, flash_petals_wide, flash_plume_long, flash_powder",
        "  maybe      = flash_embers 0.5, flash_soot 0.45",
        "  flame      = 0.2",
        "  smoke      = 5, 0.06, 0.6",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/shotgun, 1.0",
        "end",
        "",
        "# 230 GRAMS AT 250 FPS. A grenade launcher is the slowest thing anyone fires: a soft low",
        "# thump, almost no flash, and a great deal of smoke that hangs. The revolver cylinder is why",
        "# it can be walked across a room -- six of them, fast, which no other launcher here can do.",
        "flash rc_m32              # a six-shot revolver launcher: thump, not crack",
        "  light      = 130, 1.8, 3",
        "  lightcolor = 255, 212, 158",
        "  cone       = 20, 44, 72, 6",
        "  conetics   = 3",
        "  bursts     = flash_launcher_puff, flash_core, flash_soot",
        "  maybe      = flash_powder 0.5, dust_kick_ring 0.3",
        "  flame      = 0.05",
        "  smoke      = 7, 0.09, 0.8",
        "  smokeparticle = rsb_smoke_rocket",
        "  tail       = rsb/tail/rpg, 0.75",
        "end",
        "",
        "# IT BLOWS UP A CAR. This has to read as ARTILLERY rather than as a large rocket launcher, and",
        "# the difference is what happens AROUND it: a shockwave, a kick into the ground, and gas out",
        "# of the back. The blast is the event; the projectile is a detail.",
        "flash rc_cobra            # the Cobra Assault Cannon",
        "  light      = 380, 4.6, 4",
        "  lightcolor = 255, 204, 142",
        "  cone       = 40, 110, 200, 7",
        "  conetics   = 4",
        "  bursts     = flash_core, flash_plume_long, flash_plume_wide, flash_embers, flash_soot",
        "  maybe      = spk_heavy_streaks 0.7, flash_brake_smoke 0.6, rubble_concrete 0.3",
        "  flame      = 0.4",
        "  smoke      = 9, 0.12, 0.95",
        "  smokeparticle = rsb_smoke_rocket",
        "  shockwave  = 150, 0.75, 7",
        "  groundkick = kick_blast, 96",
        "  backblast  = 58, 1.25",
        "  tail       = rsb/tail/rpg, 1.0",
        "end",
        "",
        "flash rc_chaingun         # a belt gun on a mount: fast, hot, and it never stops",
        "  light      = 210, 3.0, 2",
        "  lightcolor = 255, 226, 176",
        "  cone       = 18, 50, 96, 5",
        "  conetics   = 2",
        "  bursts     = flash_core, flash_petals, spk_chaingun",
        "  maybe      = flash_powder 0.4, spk_specks_wide 0.4, flash_soot 0.3",
        "  flame      = 0.1",
        "  smoke      = 3, 0.04, 0.4",
        "  smokeparticle = rsb_smoke_gun",
        "  barrelheat = 0.5, 0.2, 0.32",
        "  barrelsmoke = rsb_smoke_barrel, 2.4",
        "  tail       = rsb/tail/lmg, 0.95",
        "end",
        "",
    ]

    # ---------------------------------------------------------------- HACX
    out += [
        "flash hx_pistol           # two pounds of 9mm: snappy and small",
        "  light      = 170, 2.6, 2",
        "  lightcolor = 255, 224, 176",
        "  cone       = 14, 36, 66, 4",
        "  conetics   = 2",
        "  bursts     = flash_core_9mm, flash_petals, spk_streaks_fine",
        "  maybe      = powder_clump 0.3, spk_specks 0.35",
        "  flame      = 0.06",
        "  smoke      = 2, 0.03, 0.28",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/pistol, 0.8",
        "end",
        "",
        "flash hx_uzi              # six pounds of 9mm, which is heavy for the round and therefore calm",
        "  light      = 175, 2.5, 2",
        "  lightcolor = 255, 220, 172",
        "  cone       = 16, 42, 76, 4",
        "  conetics   = 2",
        "  bursts     = flash_core_9mm, flash_petals, flash_powder",
        "  maybe      = spk_specks 0.4, flash_soot 0.25",
        "  flame      = 0.07",
        "  smoke      = 3, 0.04, 0.38",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/smg, 0.9",
        "end",
        "",
        "# A TAZER IS NOT A PLASMA GUN, and it has been wearing one. Electricity does not GLOW from a",
        "# point, it CRAWLS -- forks, coils, and specks that jump between the contacts. Almost no smoke,",
        "# no flame, and the light is a hard blue-white that snaps rather than blooms.",
        "flash hx_tazer            # arcs across the contacts",
        "  light      = 150, 3.4, 2",
        "  lightcolor = 168, 214, 255",
        "  cone       = 8, 18, 30, 5",
        "  conetics   = 4",
        "  bursts     = lightning_coils, lightning_forks, lightning_specks",
        "  maybe      = arc_electric_one 0.6, wisp_electric 0.4",
        "  flame      = 0.0",
        "  smoke      = 1, 0.01, 0.12",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/br, 0.6",
        "end",
        "",
        "# THE COLD ONE. See cold_blocks above for why frost needed its own bursts rather than blue",
        "# fire: the vapour falls, the crystals do not burn out, and there is no heat to shimmer.",
        "flash hx_cryogun          # a jet of cold: pale, sinking, and it bends no air",
        "  light      = 110, 1.6, 3",
        "  lightcolor = 198, 232, 255",
        "  cone       = 18, 40, 64, 6",
        "  conetics   = 3",
        "  bursts     = cryo_bloom, cryo_fog, cryo_shards",
        "  maybe      = cryo_fog 0.6",
        "  flame      = 0.0",
        "  smoke      = 0, 0.0, 0.0",
        "  tail       = rsb/tail/br, 0.55",
        "end",
        "",
        "flash hx_reznator         # HacX's energy rifle: a hard violet-white core with ozone off it",
        "  light      = 230, 3.6, 2",
        "  lightcolor = 208, 178, 255",
        "  cone       = 14, 38, 70, 5",
        "  conetics   = 3",
        "  bursts     = plasma_core, plasma_glow, plasma_ozone",
        "  maybe      = plasma_crackle_muzzle 0.55, energy_sparks_plasma 0.4",
        "  flame      = 0.0",
        "  smoke      = 1, 0.02, 0.2",
        "  smokeparticle = rsb_smoke_gun",
        "  tail       = rsb/tail/br, 0.85",
        "end",
        "",
        "flash hx_zooka            # a rocket tube somebody welded: dirty, smoky, and it coughs",
        "  light      = 280, 3.4, 3",
        "  lightcolor = 255, 200, 140",
        "  cone       = 30, 78, 140, 6",
        "  conetics   = 4",
        "  bursts     = flash_core, flash_plume_dirty, flash_embers, flash_soot",
        "  maybe      = rocket_motor 0.6, flash_brake_smoke 0.5",
        "  flame      = 0.32",
        "  smoke      = 8, 0.1, 0.85",
        "  smokeparticle = rsb_smoke_rocket",
        "  backblast  = 44, 0.9",
        "  tail       = rsb/tail/rpg, 0.95",
        "end",
        "",
        "# A NUKE BUILT IN A SHED. Bigger than the BFG and CRUDER -- the charge is the show, the release",
        "# is almost an afterthought, and it should look like something that might go wrong.",
        "flash hx_nuker            # it charges for a second and a half and then the room changes",
        "  light      = 400, 4.8, 4",
        "  lightcolor = 198, 255, 176",
        "  cone       = 44, 120, 210, 7",
        "  conetics   = 4",
        "  bursts     = bfg_glow_heavy, bfg_wave_heavy, bfg_ozone, flash_embers, flash_soot",
        "  maybe      = bfg_arcs 0.7, energy_sparks_bfg 0.6, rubble_concrete 0.25",
        "  flame      = 0.3",
        "  smoke      = 9, 0.12, 0.9",
        "  smokeparticle = rsb_smoke_flame",
        "  chargebursts = bfg_charge_motes 16, bfg_charge_arcs 10, bfg_charge_core 6",
        "  chargelight = 180, 2.4",
        "  chargelightcolor = 198, 255, 176",
        "  shockwave  = 170, 0.85, 8",
        "  groundkick = kick_blast, 104",
        "  tail       = rsb/tail/rpg, 1.0",
        "end",
        "",
    ]
    return out


# gun class -> the profile it should name, and what it was wearing before.
SHEET = [
    ("RC_Auto9",    "rc_auto9",    "pistol_9mm",  "compensated machine pistol: climbs 0.69 against a bare 9mm's 1.57, because the brake is the gun"),
    ("RC_M27",      "rc_m27",      "vp_rifle",    "a service 5.56"),
    ("RC_KSG",      "rc_ksg",      "shotgun_bullpup", "bullpup 12 gauge, 8.20 lb loaded"),
    ("RC_Shotgun",  "rc_shotgun",  "shotgun_m37", "a LIGHT pump: same shell as the KSG, 3.60 against 2.73, because it is two pounds lighter"),
    ("RC_M32",      "rc_m32",      "launcher_40mm", "six-shot revolver launcher: a shove, and fast enough to walk"),
    ("RC_Cobra",    "rc_cobra",    "rocket_rpg",  "artillery: shockwave, ground kick and backblast"),
    ("RC_Chaingun", "rc_chaingun", "machinegun_762", "30 lb loaded on a mount: climb 0.19"),
    ("HX_Pistol",   "hx_pistol",   "pistol_9mm",  "a two-pound 9mm"),
    ("HX_Uzi",      "hx_uzi",      "smg",         "heavy for the round, so it is the steady one"),
    ("HX_Tazer",    "hx_tazer",    "plasma",      "ELECTRIC, not plasma: arcs and coils, no glow, no smoke"),
    ("HX_Cryogun",  "hx_cryogun",  "plasma_carbine", "COLD -- its own frost bursts; vapour that FALLS and no heat shimmer anywhere"),
    ("HX_Reznator", "hx_reznator", "plasma_rifle", "violet-white energy with ozone"),
    ("HX_Zooka",    "hx_zooka",    "rocket_launcher", "a welded tube: dirty, smoky, and it coughs"),
    ("HX_Nuker",    "hx_nuker",    "bfg",         "a nuke in a shed: a long charge and then the room changes"),
]


def print_sheet():
    print("SHEET KEYS FOR THE WEAPONS LANE -- Robocop and HacX, the last borrowed fourteen")
    print()
    for gun, prof, was, why in SHEET:
        print('gun "%s"' % gun)
        print('  flashprofile         = "%s"' % prof)
        print('  recoilprofile        = "%s"' % prof)
        print("  %s# was `%s` -- %s" % (" " * 20, was, why))
        print()
    print("HX_Cryogun also gets an impact family of its own: name `hx_cryo` wherever its shot lands.")
    print("Every flash has its @extreme twin. Round and ejecta keys are unchanged: the cartridge guns")
    print("already name the right brass, and the energy ones throw none.")

def check_sounds(body):
    """Refuse to write a sound name SNDINFO does not declare. A dead sound name is silent and fine."""
    declared = set()
    for line in io.open(SND, encoding="utf-8", errors="replace"):
        t = line.split("//")[0].strip()
        for kw in ("$random", "$alias", "$playersound", "$limit", "$pitchset", "$volume"):
            if t.lower().startswith(kw):
                t = t[len(kw):].strip()
                break
        m = re.match(r"^([A-Za-z0-9_/\-]+)", t)
        if m:
            declared.add(m.group(1).lower())
    bad = []
    for ln in body:
        m = re.match(r"^\s*(sound|tail)\s*=\s*([A-Za-z0-9_/\-]+)", ln)
        if not m:
            continue
        n = m.group(2).lower()
        if n in ("none", "") or n in declared:
            continue
        if (n + "/int") in declared or (n + "/ext") in declared:
            continue
        bad.append(m.group(2))
    if bad:
        raise SystemExit("REFUSING TO WRITE: not declared in SNDINFO and would be silent:\n  "
                         + "\n  ".join(sorted(set(bad))))


def main():
    if "--sheet" in sys.argv:
        print_sheet()
        return
    sys.path.insert(0, HERE)
    import gen_ww2_profiles as WW2          # the shared LIGHT -> EXTREME transformer
    flashes = flash_blocks()
    body = [BEGIN, ""] + cold_blocks() + flashes + recoil_blocks()
    body += ["# LIGHT -> EXTREME: every flash again, as MORE OF WHAT IT IS. The transformer is the WW2",
             "# set's, so all ten sets grow the same way and none of them becomes a different gun at the",
             "# top setting.", ""]
    body += WW2.extreme_blocks(flashes)
    body += ["", END, ""]
    check_sounds(body)
    text = io.open(DEFS, encoding="utf-8", newline="").read()
    nl = "\r\n" if "\r\n" in text else "\n"
    block = nl.join(body)
    if BEGIN in text:
        i, j = text.index(BEGIN), text.index(END) + len(END) + len(nl)
        text = text[:i] + block + text[j:]
    else:
        anchor = "# ---- END NEW SETS"
        if anchor not in text:
            raise SystemExit("no anchor")
        text = text.replace(anchor, block + anchor, 1)
    io.open(DEFS, "w", encoding="utf-8", newline="").write(text)
    n = len([l for l in body if re.match(r"^(flash|recoil|impact|burst) ", l)])
    print("%d profiles for Robocop and HacX (%d derived, %d stated, %d flashes + their extremes)"
          % (n, len(DERIVED), len(STATED), len(DERIVED) + len(STATED) - 1))
    for gid in sorted(DERIVED):
        wb, vb, wc, empty, cap, rgr, action, _n = DERIVED[gid]
        loaded = empty + cap * (rgr / 7000.0)
        vg, e, imp = free_recoil(wb, vb, wc, loaded)
        climb = min(CLIMB_CEILING, vg * CLIMB_PER_FPS * ACTION[action]) * (0.62 if gid == "rc_auto9" else 1.0)
        print("  %-13s %5.2f lb loaded  Vg %5.2f  %6.1f ft-lb  impulse %5.3f  climb %.2f"
              % (gid, loaded, vg, e, imp, climb))


# IMPORTING A GENERATOR MUST NOT RUN IT. Bare `main()` here meant that reading this file's
# tables -- or borrowing one function from it -- REWROTE RSBDEFS.txt as a side effect. It
# silently reverted eleven round looks mid-edit once, and ran a second time when another
# generator imported this one for its extreme transformer.
if __name__ == "__main__":
    main()
